### ISSUE TITLE
Amcrest ASH26 Camera Unavailable

### ISSUE THREAD

**Issue by WorldOfMaze** [dermotduffy/frigate-hass-card#1675] opened 2024-11-05 04:22 UTC
**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml
{
  "ha_version": "2024.11.0b1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0",
  "date": "2024-11-05T04:08:34.536Z",
  "frigate_version": {},
  "lang": "en",
  "timezone": "America/Los_Angeles",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.amcrest_camera",
        "live_provider": "auto",
        "title": "Outdoor Kitchen",
        "icon": "mdi:grill-outline"
      }
    ],
    "live": {
      "show_image_during_load": false,
      "draggable": true,
      "preload": false,
      "zoomable": true,
      "lazy_load": true
    }
  }
}
```

**[REQUIRED] Description of problem:**

The camera entity ```camera.amcrest_camera``` shows properly in the Frigate integration but when I add a Frigate Card for this entity I get ```Camera unavailable```.  I have 2 other cameras, both Reolink Duo 3 PoE, which work fine.  I also tried Chrome with the same results.

![image](https://github.com/user-attachments/assets/1717bf6a-4bcb-41fa-a3cd-c8f96fbd56c2)

**[OPTIONAL] Last working release (if known):**

This is a new installation of Frigate, the Frigate Integration, and the Frigate Card.

**[OPTIONAL] Javascript errors shown in the web inspector:**

Not sure if this is relevant or not, but these 3 lines show in Developer Tools when I filter by ```camera.```
![image](https://github.com/user-attachments/assets/4278a4c5-c71d-442e-a23d-21802dbb0a6e)

```text

```

**[OPTIONAL] Additional information:**

**Comment by dermotduffy** [comment] 2024-11-06 16:03
I would guess your camera is legitimately being marked as unavailable by Frigate. You could keep an eye on the camera state field by going here and looking up your camera (https://$YOUR_HA_INSTANCE/developer-tools/state), I'd bet it's periodically `unavailable`. The cause for that might be visible in your Frigate logs, but is ultimately not related to the card.

I would recommend you try one of the new betas though, as it lowers the impact of camera unavailability on the card:  https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.8

**Comment by dermotduffy** [comment] 2024-11-26 04:21
Please re-open if there is more to discuss here. Thanks.

**Closed by dermotduffy** 2024-11-26 04:21 UTC
Labels: question
