### ISSUE TITLE
Card does not show up in HACS search list

### ISSUE THREAD

**Issue by sygys** [dermotduffy/frigate-hass-card#451] opened 2022-03-06 10:10 UTC
Maybe a noob question but i cant seem to find this card in the frontend part of HACS. Adding the repository tells me it is allready in HACS. But searching for frigate doesnt work. 

Did someone remove this from HACS?

**Comment by sygys** [comment] 2022-03-06 10:24
It seems to be in hacs but when searching nothing shows up i had to manual scroll and find it..

**Comment by dermotduffy** [comment] 2022-03-06 16:30
It's definitely still in HACS. Do you have it already installed? A quick test shows that HACS seems to filter out search results that are already installed, so that would be my guess?

**Comment by sygys** [comment] 2022-03-06 19:19
I indeed found it. I would have hoped this card would show the videofeeds like the frigate addon does. For some reason the feeds in frigate never buffer and always just work instant. But in Lovelace no matter what card I use there is always buffering and stuttering. I don't understand why. I can't seem to fix it

**Comment by dermotduffy** [comment] 2022-03-06 19:27
> But in Lovelace no matter what card I use there is always buffering and stuttering. 

Is there a large network distance between your HA installation and your Frigate backend? Could your HA instance be underpowered? Do other non-Frigate video feeds work okay?

**Comment by dermotduffy** [comment] 2022-03-09 03:10
Closing this out as I don't believe the issue is related to the card, please re-open if you have evidence/theory to the contrary. Thanks!

**Closed by dermotduffy** 2022-03-09 03:10 UTC
Labels: question
