### ISSUE TITLE
Videos not displayed/not playing on Safari iOS/MacOS

### ISSUE THREAD

**Issue by AndLindemann** [dermotduffy/frigate-hass-card#840] opened 2022-09-26 16:02 UTC
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:** 4.0

**Last working release (if known):** n/a

**Browser and Operating System:** Safari 16 on MacOS, Safari on iOS 16

**Description of problem:**
Sometimes (a decent percentage) videos are not playing when the card is loading or when the card refreshed/swaps to another camera.
My guess is this is related to these Javascript errors which might be some Safari specific behavior and have something to do with how video+audio is being loaded in relation to user interactions.
Usually clicking on the card makes the video play in these circumstances but it would of course be nice it the card would play the video right away and not rely on a user interaction for playback. It doesn't happen all the time, but quite often.

Potentially for the same reason often the Thumbnails bar is missing images of the clips. A random number of images of clips might be missing (see below screenshot where the first one on the left is missing), sometimes more, sometimes less. Clicking on the blank spot will still take you to the playback of the clip, so the data seems to be there, just the image is not being displayed.

**Javascript errors shown in the web inspector (if applicable):**

```
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
(anonyme Funktion)
rejectPromise
play
play — frigate-hass-card.js:401:281
play — frigate-hass-card.js:419:292
play — frigate-hass-card.js:551:600
play — frigate-hass-card.js:520:755
l — frigate-hass-card.js:286:2731
autoPlay — frigate-hass-card.js:307:2894
autoPlay
dispatchEvent
Dg — frigate-hass-card.js:107:115622
e_ — frigate-hass-card.js:271:25983
_storeMediaLoadedInfo — frigate-hass-card.js:307:5957
_storeMediaLoadedInfo
handleEvent — frigate-hass-card.js:17:7372
dispatchEvent
Dg — frigate-hass-card.js:107:115622
aw — frigate-hass-card.js:307:1443
lw — frigate-hass-card.js:307:1507
(anonyme Funktion) — frigate-hass-card.js:480
handleEvent — frigate-hass-card.js:17:7372
dispatchEvent
Dg — frigate-hass-card.js:107:115622
e_ — frigate-hass-card.js:271:25983
t_ — frigate-hass-card.js:271:25958
(anonyme Funktion) — frigate-hass-card.js:274
handleEvent — frigate-hass-card.js:17:7372
play — frigate-hass-card.js:401:281
```

**Additional information:**
<img width="1433" alt="Bildschirmfoto 2022-09-26 um 17 58 35" src="https://user-images.githubusercontent.com/4157845/192325471-a99c09b5-3863-4f00-8339-36040f834856.png">

<img width="861" alt="Bildschirmfoto 2022-09-26 um 18 04 06" src="https://user-images.githubusercontent.com/4157845/192325932-e07e8b41-7818-47d6-bfcb-d84684be81fc.png">

**Comment by dermotduffy** [comment] 2022-09-27 02:47
Thanks for the report @AndLindemann ! First, do you see **both** of these issues in Safari both on MacOS **and** iPhone, or does it vary per issue?

> Sometimes (a decent percentage) videos are not playing when the card is loading or when the card refreshed/swaps to another camera.

Just to confirm, I think "not playing" means it loads okay but you need to manually press the play button -- right? If yes, then indeed I suspect some Safari specific logic is trying to prevent "random" Javascript from playing videos when the user may not want that. Completely understandable for the web at large, just not in this case :-)

> Potentially for the same reason often the Thumbnails bar is missing images of the clips. A random number of images of clips might be missing (see below screenshot where the first one on the left is missing),

Huh. I really doubt that's related. If you're comfortable doing so, would you mind using the web inspector ([instructions for Safari](https://blog.hubspot.com/website/how-to-inspect#Safari)) to select that 'blank' thumbnail and paste the `<img>` element you find?

**Comment by dermotduffy** [comment] 2022-09-27 02:48
PS: Can you hold down the Frigate menu button for a few seconds and paste the diagnostics that show up?

**Comment by AndLindemann** [comment] 2022-09-27 09:58
Separating the 2 issues:

1) Video not playing: I see this only on MacOS currently. iOS (Home Assistant App) seems to load&play videos just fine.
On MacOS, the video loads but it isn't displayed and/or doesn't play automatically. After interaction, like pressing the play button, it plays fine.

2) Missing Thumbnails I see on both MacOS and iOS, also within the iOS Home Assistant App. 
Here you can see the first thumbnail missing in the HASS iOS app. But there's varying degrees there, I have also seen more than one or even all of the thumbs not displaying.

![IMG_3736](https://user-images.githubusercontent.com/4157845/192495955-71093168-d0f5-4d3b-a1e1-3c5b0179654a.jpeg)

I looked through the Web Inspector on Safari (MacOS) and it looks like the img tags with the content are there, just the display isn't working correctly. Potentially a CSS issue?

Here's a screenshot showing that the img tag has content for the inlined image, but the Thumbnails are not displaying:
<img width="848" alt="Bildschirmfoto 2022-09-27 um 11 50 27" src="https://user-images.githubusercontent.com/4157845/192496404-eab5a9a6-ba5e-4c93-b07d-63ff2817e833.png">

**Comment by dermotduffy** [comment] 2022-09-28 04:47
I believe I have figured out the thumbnail issue. I cannot reproduce the video playing issue though, do you have any particular reproduction steps?  

I'm testing on Safari Version 15.6 (Monterey 12.5).

**Comment by dermotduffy** [comment] 2022-09-28 13:35
Update: Also cannot  reproduce with Safari Version 16.0 (17614.1.25.9.10, 17614). What I'm doing:

* Open the clips gallery, choose a clip, and scroll next/previous to move forwards/backwards though the clips. They reliably auto play.
* OR: Set view to 'clip' (Most recent clip). Clip reliably plays on card load.

**Comment by AndLindemann** [comment] 2022-09-28 15:52
Thanks for checking. Here's a quick clip I recorded, showing what's happening on my end - occasionally.
The video starts playing and then after a few seconds it blanks out. If I then click on play, it continues:

https://streamable.com/fovy11

**Comment by dermotduffy** [comment] 2022-09-29 03:31
@AndLindemann Thanks for the video. Weird. Does it actually start playing (I can't tell) and then blank, or is it just a static frame followed by a blank? Would you mind trying in an incognito/private window and see if it still happens (could it be an extension of some kind?).

> For reference, my HA website is configured to use HTTPS.

(I am also testing on https)

**Comment by dermotduffy** [comment] 2022-09-29 03:47
I can get this error to show in the console if I specifically disable auto play in the settings:

<img width="786" alt="Screen Shot 2022-09-28 at 8 45 39 PM" src="https://user-images.githubusercontent.com/1136829/192934158-11c04028-4b02-4d91-89ab-4a06a79cba38.png">

(Note: I can't get the blanking to happen, but it refuses to play and logs the error)

**Comment by AndLindemann** [comment] 2022-09-29 11:35
Ah.... omg, thanks. 
I had all websites set to never auto-play. Have changed it for my HA site and it playback is fine now. Good hint! 👍 

So just the thumbnail issue left then.

**Comment by AndLindemann** [comment] 2022-09-29 13:41
Yeah, saw your commit. I'll be away over the weekend anyway, so I'll probably just wait for the 4.1 release. 
Thanks for your help and your effort on this, the card turned out to be really good. :)

**Comment by dermotduffy** [comment] 2022-09-29 13:48
OK! I'm going to close this for now to clean up the issues. If you try 4.1 and it still doesn't work, definitely re-open. Thanks!

**Closed by dermotduffy** 2022-09-29 13:48 UTC
Labels: bug
