### ISSUE TITLE
Timeline bugs: Date-picker + recordings / Hour label only loading a single hour

### ISSUE THREAD

**Issue by kirsch33** [dermotduffy/frigate-hass-card#1240] opened 2023-08-09 21:21 UTC
**Is your feature request related to a problem? Please describe.**
I have all my cameras set to record 24/7. Very pleased with how the card displays events with the timeline and snapshots/etc, but unless I am missing something there isn't an ability to arbitrarily navigate to a time and 'seek' thru 24/7 recordings.

**Describe the solution you'd like**
In an ideal world we could get something like Nest Sightline (see https://github.com/blakeblackshear/frigate/issues/2230 on the Frigate repo) but I imagine that is outside the scope of this card. Still, some approximation of it, even crudely, to quickly scroll thru 24/7 recordings would be much appreciated.

**Comment by dermotduffy** [comment] 2023-08-10 02:43
Hi @kirsch33 , thanks for the feedback. Can you help me understand how that differs (apart from aesthetics) from the existing video scrubbing support, seems kind of similar?

![video-scrubbing](https://github.com/dermotduffy/frigate-hass-card/assets/1136829/ef1b4dd3-537d-4eda-acba-6732d27131ab)

**Comment by kirsch33** [comment] 2023-08-12 17:25
@dermotduffy turns out the mini-timeline is exactly what i was missing all along. when i first setup the card, i hated the "full" timeline so turned off every timeline related setting. the clip you posted above has shown me the error of my ways. 

mini-timeline is awesome and takes this card to a whole new level!

**Comment by kirsch33** [comment] 2023-08-14 01:50
@dermotduffy i stand by that mini-timeline is awesome,but after messing around this weekend i think i am either 1) using it wrong 2) have an incorrect setup or 3) discovered some glitches in behavior.

i made a screen recording below. Heres the behavior im noticing that I dont think is correct:

1. at the start of the video, you can see i pick a date of august 1st and a time around 10am, but i click above the labeled hour markers (in the events ribbon section), and for some reason it loads august 11th at 8am. this happens ALOT, and for some reason always that specific date of aug 11 8am. 
2. i manged to figure out that by clicking specifically on the area of the timeline that has the hour markers, it loads the correct time. in this example it loads around 6:30am on august 4th, which is about where i clicked. and at first it is correctly seeking thru time. so all good. but you can see that once I scrub/seek out of that hour long window, past 7am, even though the scrubbing position marker says that i'm far past that point in time it stops updating entirely.

for item #1, im not sure why that specific date is coming up, but especially on mobile its frustrating because its very difficult to click exactly on the hour markers to get it to behave somewhat correctly, that is until I hit issue #2.

anyways, I'm going to re-open this, even if it is user error. please let me know your thoughts!

https://github.com/dermotduffy/frigate-hass-card/assets/37373320/5a6269ef-cbba-4543-97ac-2aa446446210

**Comment by dermotduffy** [comment] 2023-08-14 03:11
I don't think this is user error.

Parts of the timeline that are supposed to interact (FYI):

* Click an event, it loads that event.
* Click the background of the timeline OR the hour marker, it loads the recording nearest that time where you clicked.

> at the start of the video, you can see i pick a date of august 1st and a time around 10am, but i click above the labeled hour markers (in the events ribbon section), and for some reason it loads august 11th at 8am.

1. Notice in the video (at 0:13s) when you change the date, the background of the timeline is black. This is because it has not yet joined together the thousands of 10s segments into a recording. Usually that takes a few seconds, but here doesn't seem to happen. I can repeat that too, if I use the date-picker it doesn't seem to correctly load the events/recordings at all until the timeline is interacted with again.

I'm wondering if this is something to do with it, and the 8am is just purely the earliest recording it happens to have loaded.

**Suggestion**: Try manually scrubbing backwards (instead of date-picker), does this cause the timeline clicking to load the correct position in the recording?

2. This is also definitely wrong. As you scrub to the right, the carousel should move to select the next media item, as in the following example:

![timeline-scrub-small](https://github.com/dermotduffy/frigate-hass-card/assets/1136829/a1453a13-d3c0-44c9-bbb2-6e5c4729b922)

Try this: Instead of clicking on the hour marker, click on the hour itself (i.e. on the main timeline

I think this is a separate bug, when you click on the timeline it should load multiple hours worth of recordings allowing you to scrub left/right through them. This seems to work fine for me when I click the background of the timeline (i.e. the main horizontal piece where the events show up -- click anywhere there that is not an event), but doesn't when I click on the hour marker itself.

**Comment by kirsch33** [comment] 2023-08-14 13:38
@dermotduffy i think your descriptions above nailed it. separate bugs, but both definitely present. 

for number 1, if i do as you say by foregoing the date picker and just manually zoom out/scrub on the ribbon of the timeline, it behaves as intended by loading the appropriate amount of video and scrubbing across time (even multiple hours). so this is the intended behavior.

using the date picker causes things to go haywire, and its hard to recover from (without reloading the view) because the only way to get it to load recordings then is by using the hour markers, but as you say that leads to bug number 2. 

this is all more of an issue on mobile where it is more difficult to precisely select one portion of the timeline vs the other (my index finger is almost the width of the entire timeline when in portrait mode on my iPhone 13). 

here is one other thing ive noticed that I'm not sure you will agree is a 'bug' or not, or maybe just a feature request. if you load a live view with mini timeline active, and instead of clicking anywhere on the timeline just instead scrub backwards (which is the most natural way to operate it i think), nothing will happen. it doesn't actually register the desire to load any recordings unless first interacted with by a specific click. i most often start scrubbing backward in time then have to remember to click it after realizing my error. is this intentional?

**Comment by kirsch33** [comment] 2023-08-14 14:35
> > here is one other thing ive noticed that I'm not sure you will agree is a 'bug' or not, or maybe just a feature request. if you load a live view with mini timeline active, and instead of clicking anywhere on the timeline just instead scrub backwards (which is the most natural way to operate it i think), nothing will happen. it doesn't actually register the desire to load any recordings unless first interacted with by a specific click. i most often start scrubbing backward in time then have to remember to click it after realizing my error. is this intentional?
> 
> I can't tell if this is a bug or a misunderstanding. If you scrub backwards from live view it should load the _events_ from the past in the media viewer and let you scrub over those (i.e. the shorter video clips just when events happen, not the longer recordings that are each 1 hour long). Your setup seems very recording and 24x7 oriented (which I suspect is why you found such good bugs that weren't already spotted) -- so I can understand how this may not be what you expect.
> 
> So you'd see the live camera replaced with the most recent event, and if you scrub **within** that event on the timeline it would scan back/forwards in the video.
> 
> I think the feature request could be: Allow it to be configured such that instead of loading the event media, it loads the recording media.

yes! exactly. maybe that belongs in a different thread however, but yes that would be what makes sense in my situation.

**Comment by dermotduffy** [comment] 2023-08-14 14:42
Filed a new feature request for that, I'll use this issue for the two bugs. Thanks for the reports!

**Comment by flyize** [comment] 2023-08-22 18:29
Just found this after wondering how to do it. Glad to see you've got it on the radar!

**Comment by dermotduffy** [comment] 2024-02-03 23:38
OK, I think the small PR now merged fixes problem #1. I can no-longer reproduce problem 2, I get the same behavior clicking the hour marker or the background. I also implemented the feature requested that this issue created.

So for now, I'm going to mark this as closed. After the next release, if you're still seeing either of these issues, please re-open! Thanks.

**Closed by dermotduffy** 2024-02-03 23:38 UTC
Labels: bug
