### ISSUE TITLE
Cannot download recordings

### ISSUE THREAD

**Issue by doctorttt** [dermotduffy/frigate-hass-card#1199] opened 2023-06-12 02:52 UTC
Hi, please see the screenshots attached. The download function doesn't work for both desktop and cellphone. When I click the download icon (the blue arrow pointing downward) under the recording section of any camera I have configured using the Lovelace card, nothing will happen. On a web browser of a desktop, I would get "failed - no file".  I can 100% confirm that the recording files are available.  On cell phone, clicking the download button does nothing, not even an error message. 

I'm using the latest version of Frigate lovelace: 5.1.1; latest version of frigate 0.12.1; HA version 2023.6.1; HACS version 1.32.1

![image](https://github.com/dermotduffy/frigate-hass-card/assets/132242705/8237e237-e9e3-421d-a640-f4bbe56759bd)

![image](https://github.com/dermotduffy/frigate-hass-card/assets/132242705/593e464e-d419-4f0c-a16b-d517c6ceaf9a)

**Comment by dermotduffy** [comment] 2023-06-12 02:57
I can reproduce this, but only on dowloading recordings. Same for you? (i.e. Clips and Snapshots work ok?)

**Comment by doctorttt** [comment] 2023-06-12 03:39
> I can reproduce this, but only on dowloading recordings. Same for you? (i.e. Clips and Snapshots work ok?)

Thanks for looking into this issue. Yes, Clips and Snapshots work ok - able to hit the download button and download the corresponding file.

**Comment by dermotduffy** [comment] 2023-06-17 03:43
Single byte bug! Added tests. Will be in the next release,

**Closed by dermotduffy** 2023-06-17 03:43 UTC
Labels: bug

**Comment by doctorttt** [comment] 2023-06-17 03:56
Thank you and looking forward for the next release.

**Comment by doctorttt** [comment] 2023-07-05 00:54
Hi @dermotduffy. It's still not working. I did a test with Chrome on my windows desktop and I updated my frigate lovelace to the latest version. Please see the error message below and please advise. Thanks 

![image](https://github.com/dermotduffy/frigate-hass-card/assets/132242705/e960d66d-e4f5-4d52-b52d-cabadf83b61a)

![image](https://github.com/dermotduffy/frigate-hass-card/assets/132242705/fc1f851d-7cb7-4149-b388-69915ed1ba33)

**Comment by dermotduffy** [comment] 2023-07-05 01:38
@doctorttt My theory is you are still using the old version, as ThisWorksForMe(TM) and did not previously. I'd guess your browser(s) are still caching the old content.

Please check your Javascript console (F12 in Chrome) and you'll see the version number printed under ' FRIGATE-HASS-CARD ', or alternatively just hold down the Frigate menu icon (in the card) for a few seconds and it will give you diagnostics -- paste those diagnostics here.

**Comment by doctorttt** [comment] 2023-07-09 05:00
> @doctorttt My theory is you are still using the old version, as ThisWorksForMe(TM) and did not previously. I'd guess your browser(s) are still caching the old content.
> 
> Please check your Javascript console (F12 in Chrome) and you'll see the version number printed under ' FRIGATE-HASS-CARD ', or alternatively just hold down the Frigate menu icon (in the card) for a few seconds and it will give you diagnostics -- paste those diagnostics here.

Sorry for the late reply. I was busy with work and family. I did try F12 in Chrome and got the screenshot below.  For the second screenshot, I just wanted to show that I can click on each recording box and the recording will start playing on my browser. I just can't download for some reasons.  

![image](https://github.com/dermotduffy/frigate-hass-card/assets/132242705/a29e3372-ef28-4668-84ef-2328e4dce8c5)

![image](https://github.com/dermotduffy/frigate-hass-card/assets/132242705/ae7e57ee-5d3e-4b3c-afb6-56947f37bd01)

**Comment by PovilasID** [comment] 2023-07-14 17:44
Hey I am experiencing probably the same bug.
I am on 5.2.0 version (@doctorttt  it was listen in Console tab after you press F12)
However... I am sometimes getting a download of the recording and sometimes... not.  It is intermittent. I know those are just amazing to track down. I am sorry in advance. It happens almost every other time I click download button. It looks like that if I am downloading already it download video but if chose to download a record for the first time I get download.htm file or files instead. I get two download.htm files at same time. Maybe I clicked twice. 
It has to mentioned I am using cloudflared to access my Frigate instance remotely. My Frigate instance is also served via LTE, so...

**Comment by dermotduffy** [comment] 2023-07-15 19:40
@doctorttt Can you hold down your Frigate menu button (in the card) for a few seconds and paste the diagnostics that show up, into this issue?

@PovilasID Can you do the same?

**Comment by PovilasID** [comment] 2023-07-15 21:24
Here you go
https://gist.github.com/PovilasID/712d0f9c9cb78ab531e693546e100d34

**Comment by doctorttt** [comment] 2023-07-16 00:33
I also posted mine there: https://gist.github.com/PovilasID/712d0f9c9cb78ab531e693546e100d34

**Comment by dermotduffy** [comment] 2023-07-16 23:15
Well, you're both definitely using v5.2.0 :-) I've found that sometimes it can take a while between click and the download happening for large videos -- this is because the backend is assembling the individual 10 second segments behind the scenes into one single file, and this may take a little bit of time. @PovilasID Is it possible the "every other time" is just because you're not waiting long enough for the first click to work?

The `download.htm` piece is strange though -- I never get that somehow (although I'm on a more cutting edge version of Frigate, `0.13.0-ADED314`).

**Comment by doctorttt** [comment] 2023-07-18 00:47
@dermotduffy @PovilasID guys, I think I figured out what happened. I had the frigate log opened while troubleshooting this recording download issue in HA. I suddenly saw a bunch of errors in the frigate log complaining about not having enough space. Logically, I immediately changed the cache size in frigate and BAM! the downloading function in the lovelace card works.  In short, the cache size in frigate must be large enough to convert a one hour clip. In my case, a one-hour recording for me is about 2GB. 

![image](https://github.com/dermotduffy/frigate-hass-card/assets/132242705/5262e059-b3fa-4cae-994e-5cc9f6971890)

@dermotduffy for what is worth, I'm also using the most cutting edge version (but not official yet) ```0.13.0-3B21F86``` with tensorrt Nvidia libraries updated to handle RTX4000 series gpu for detection using yolo's. :)

**Comment by dermotduffy** [comment] 2023-07-18 02:24
@doctorttt Aha! Good find, it makes sense! @PovilasID Do you think this could be the issue for you too? If yes, I will add an FAQ entry on this.

**Comment by PovilasID** [comment] 2023-07-18 08:12
@doctorttt Yah you are right I check the logs for frigate and saw `Error writing trailer of /tmp/cache/durys-%Y%m%d%H%M%S.mp4: No space left on device` I am running at capacity (I am just letting Frigate delete oldest video when it runs out space) but that means there is always not enough cash space. 
@dermotduffy Yah can confirm... Why did not look at frigate's logs in first place? Anyway I think frigate is introducing a download for records function in 0.13, so maybe it can be relied on. Also since I was having issues I used one of the tools that for downloading streams when I needed a full hour record. (They pull a m3u8 file and download piece by piece and stich the smaller files on client side). So it's a quick work around.
Cash size increase would be a good addition to docs.

**Comment by doctorttt** [comment] 2023-07-18 16:04
> Thanks @PovilasID .
> 
> @doctorttt Can you include the configuration you used to bump the cache size? I'll include those in the doc update.

yes sure, I'm using Frigate's docker in Unraid. Changing the cache size requires adding ```--mount type=tmpfs,target=/tmp/cache,tmpfs-size=5000000000``` under Extra Parameters. The numerical figure is the cache size in bytes. User just need to increase the cache size larger to accommodate a one-hr recording download.  The size of the one-hr recording will depend on the camera configuration like resolution, bit rate, frames, etc. The higher the settings, the larger the recording and vice versa. 

@dermotduffy separately as you already know, Frigate 0.13 will come with a function to export recordings. I tested this function in the beta version but it doesn't require the cache size to be large enough like the issue we ran through in the lovelace card in HA. Is it possible to make the download recording function the lovelace card in HA not to use cache size? 

![image](https://github.com/dermotduffy/frigate-hass-card/assets/132242705/dbb9b960-b4ce-468a-8909-b3b0ca0f8aea)

**Comment by NickM-27** [comment] 2023-07-22 15:34
Using the export function from the cards perspective will be more difficult. Frigate responds with an http status if the export was able to start or not. The export / assembly of the mp4 file can still take some time depending on how large the file is so the download would still not be available. 

That is why the Frigate UI for example just shows the exports in a list and doesn't show a download popup immediately.
