### ISSUE TITLE
Live provider `webrtc-card` never unloads camera connection unless tab is closed

### ISSUE THREAD

**Issue by irakhlin** [dermotduffy/frigate-hass-card#1389] opened 2024-03-02 04:22 UTC
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
v5.2.0
**Last working release (if known):**
Previously unnoticed
**Browser and Operating System:**
Windows 11 with both Firefox and Chrome.

**Description of problem:**
This issue was detected when performing a wireshark capture for an unrelated issue. As seen from the diagnostic information camera is configured to lazy unload live provider as "all". Testing was performed with both the "webrtc-card" and "go2rtc" live provider showing the following:
- go2rtc provider: opening home assistant and selected the dashboard with the camera begins to  show UDP traffic on port 8555, navigating to a different dashboard results in the traffic terminating within ~5 seconds as expected. Closing the tab produces the same results. (expected).
- webrtc-card provider: configuration tested with mode set as "webrtc,mse" and "webrtc,webrtc/tcp,mse" produce essentially the same results. In both firefox and chrome. Navigating to the camera tab begins significant amount of UDP (or TCP depending on the config) traffic. Navigating to another dashboard **does not** terminate the traffic. The connection to the camera seems to run indefinitely and was monitored for at least 10 minutes after navigating away from the camera. Refreshing the page **does** terminate the traffic within ~ 5 seconds. 

**Frigate card diagnostic information**

```json
{
  "ha_version": "2024.2.5",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
  "date": "2024-03-02T04:05:53.030Z",
  "frigate_version": {
    "ec2c8925d22540a93b09b04b2678f925": "5.0.1/0.13.0-771f518"
  },
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.camera-name",
        "live_provider": "webrtc-card",
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ],
          "stream": "camera-name"
        },
        "engine": "frigate",
        "frigate": {
          "camera_name": "camera-name",
          "url": "https://{removed}"
        },
        "webrtc_card": {
          "url": "rtsp://{removed}:{removed}@{removed}:8554/camera-name",
          "mode": "webrtc,mse",
          "ui": true,
          "style": ".header {bottom: 6px} .mode {position: absolute; bottom: 0px; left:50%;} .screenshot {display: none}"
        }
      }
    ],
    "view": {
      "default": "live",
      "dark_mode": "off"
    },
    "performance": {
      "profile": "high"
    },
    "live": {
      "preload": false,
      "zoomable": true,
      "auto_play": "all",
      "auto_pause": "never",
      "auto_mute": "never",
      "auto_unmute": "all",
      "audio": true,
      "controls": {
        "title": {
          "mode": "none"
        }
      },
      "lazy_unload": "all"
    },
    "menu": {
      "style": "hidden",
      "position": "top",
      "alignment": "right",
      "buttons": {
        "cameras": {
          "enabled": false
        },
        "substreams": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        },
        "recordings": {
          "enabled": true
        },
        "expand": {
          "enabled": true
        },
        "mute": {
          "enabled": true
        }
      }
    },
    "cameras_global": {
      "webrtc_card": {
        "background": true,
        "ice_servers": [
          {
            "urls": [
              "stun:{removed}"
            ]
          },
          {
            "urls": [
              "turn:{removed}"
            ],
            "username": "{removed}",
            "credential": "{removed}"
          }
        ]
      }
    },
    "dimensions": {
      "aspect_ratio_mode": "dynamic"
    }
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment] 2024-03-02 04:25
(Thank you for the high quality bug report!)

**Comment by maniacaris** [comment] 2024-03-30 17:23
This can also be observed in the go2rtc logs in debug mode:

>2024-03-30 17:04:28.987560735  [INFO] Preparing new go2rtc config...
2024-03-30 17:04:29.071032412  [INFO] Got IP address from supervisor: 10.0.0.12
2024-03-30 17:04:29.126712237  [INFO] Got WebRTC port from supervisor: 8555
2024-03-30 17:04:30.090284417  [INFO] Starting go2rtc...
2024-03-30 17:04:30.206743633  12:04:30.206 INF go2rtc version 1.8.4 linux/amd64
2024-03-30 17:04:30.208640677  12:04:30.208 INF [api] listen addr=:1984
2024-03-30 17:04:30.209078609  12:04:30.208 INF [rtsp] listen addr=:8554
2024-03-30 17:04:30.209533355  12:04:30.209 INF [webrtc] listen addr=:8555
2024-03-30 17:04:38.986244695  [INFO] Starting go2rtc healthcheck service...
#Start watching Doorbell camera
2024-03-30 17:06:41.499103463  12:06:41.498 DBG [webrtc] new consumer src=Doorbell
2024-03-30 17:06:42.508113396  12:06:42.507 DBG [webrtc] new consumer src=Doorbell
#Switch to Garage Side camera
2024-03-30 17:06:55.320136813  12:06:55.319 DBG [webrtc] new consumer src=Garage_Side
2024-03-30 17:07:19.989027561  12:07:19.988 DBG [webrtc] new consumer src=Doorbell
#Garage stream cuts out, reloads
2024-03-30 17:07:34.545596714  12:07:34.545 DBG [webrtc] new consumer src=Garage_Side
#Switch to Back Yard camera
2024-03-30 17:07:55.390804054  12:07:55.390 DBG [webrtc] new consumer src=Back_Yard
2024-03-30 17:08:00.300444571  12:08:00.300 DBG [webrtc] new consumer src=Doorbell
2024-03-30 17:08:13.792080836  12:08:13.791 DBG [webrtc] new consumer src=Garage_Side
#Back Yard stream cuts out, reloads
2024-03-30 17:08:34.797659202  12:08:34.797 DBG [webrtc] new consumer src=Back_Yard
2024-03-30 17:08:39.302985512  12:08:39.302 DBG [webrtc] new consumer src=Doorbell

In this case, an iOS client was used with the Home Assistant Companion app. The stream I'm viewing cuts out when the other streams reconnect in the background, but most of the time (not always) the stream being viewed recovers. All the streams disconnect as expected the the app enters the background.

**Comment by dermotduffy** [comment] 2024-04-15 02:56
Closing this as a I think it's WAI, but please let me know if you disagree.

**Closed by dermotduffy** 2024-04-15 02:56 UTC
Labels: bug

**Comment by irakhlin** [comment] 2024-04-15 17:35
@dermotduffy just want to point out this issue is still happening, I can reproduce and track both via wireshark capture and the go2rtc addon web page status.

When using the webrtc-card provider, and using the newest version of the go2rtc addon, I can navigate to the camera live stream via the card, then to another home assistant tab multiple times and each time the total "Online" sessions for the camera connections increase and maintain. A forced browser refresh drops the number back down for all connections. 

This can also be shown by accessing the firefox "about:webrtc" debug panel, the following is the result of navigating to and away from the card (changing home assistant dashboards) 5 times.

![image](https://github.com/dermotduffy/frigate-hass-card/assets/12637936/fcdd83b8-7e02-4c90-a62f-560431052e2a)

**Comment by dermotduffy** [comment] 2024-04-15 17:42
> @dermotduffy just want to point out this issue is still happening, I can reproduce and track both via wireshark capture and the go2rtc addon web page status.

See [this comment](https://github.com/dermotduffy/frigate-hass-card/issues/1389#issuecomment-2043899853): I agree it is still happening, but my sense is that it's working as intended since the user has _specifically_ asked the WebRTC card to run in the background. Both the WebRTC card, or WebRTC card embedded in the Frigate card, behave the same way when configured like this.
