### ISSUE TITLE
Image is not shown when returning back to HA tab

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#495] opened 2022-03-23 18:23 UTC
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** v3.0.0

**Browser and Operating System:** Firefox, iPhone

**Description of problem:**

Sometimes when you switch back to HA tab, image is not shown(not even stock image). At that time you can only see the menu and after couple of seconds image reappears(I think because of `refresh_interval`) . 

I don't how to reproduce this every time, but it's happening casually.

![frigate_card](https://user-images.githubusercontent.com/24360494/159766587-8536dda3-fb86-4516-89d8-df5f888d1ec0.png)

**Comment by dermotduffy** [comment] 2022-03-24 02:12
It showing the stock image for a few seconds would be expected. This is related to: https://github.com/dermotduffy/frigate-hass-card/issues/398 . It can only show the stock image because the HA access token it has is expired, and if it _tried_ to show the real image, it'd generate a rejection on the HA side.

However, I cannot currently explain a blank image...

**Comment by dermotduffy** [comment] 2022-05-14 14:50
Does this still happen @peledzius ? Still trying (& failing) to reproduce this.

**Comment by dermotduffy** [comment] 2022-05-14 16:01
What I've tried (in Firefox):

Setup:

* Open a dashboard with just a Frigate card on it, in the `image` view set to a camera.

Test variety 1:

* Minimize the firefox window and open it 15 minutes later.

Test variety 2:

* Open a new tab in the window and revisit the HA tab 15 minutes later.

In both cases look for any (even momentary) black/empty images.

Can't get it to misbehave. I can get it to show the stock Frigate card image for a second, but that's WAI. 

Am I testing the wrong thing? Or other advice on how to reproduce this?

**Comment by peledzius** [comment] 2022-05-20 22:53
@dermotduffy yes, it still occurs randomly.

For this behaviour you don't need to wait 15 minutes, it's enough to switch between tabs. I tried pressing Ctrl+Tab many times(switching between tabs), but couldn't reproduce. All the times stock image was shown for a second as expected.

I think it's not worth to explore this issue anymore, it could be not related to card? + I'm only one with this issue. 

Thanks!

**Comment by dermotduffy** [comment] 2022-05-21 02:25
OK @peledzius . I'll close this for now, and if you (or I) find a way to reproduce we can revisit. Thanks!

**Closed by dermotduffy** 2022-05-21 02:25 UTC
Labels: bug

**Comment by peledzius** [comment] 2022-11-22 05:04
Found one way to reproduce this:
1. Open dashboard with Frigate card default view set to `image`
2. Quickly switch to other tab before image loads(may need couple of tries)
3. Return back to dashboard tab and you should see blank image

Reproduced this with v4.0.0 in both Chrome and Firefox 

One different thing I noticed from initial problem that image never appears(it's always blank).

**Comment by spacebares** [comment] 2022-11-22 06:10
https://user-images.githubusercontent.com/57186372/203237966-f339c473-fc41-4b18-acea-8ae2b282d669.mp4

im having a hard time reproducing this myself.
i tried [this massive image file](https://effigis.com/wp-content/uploads/2015/02/DigitalGlobe_WorldView2_50cm_8bit_Pansharpened_RGB_DRA_Rome_Italy_2009DEC10_8bits_sub_r_1.jpg) for a load test.

**Comment by peledzius** [comment] 2022-11-22 06:46
Yeah, meant switching browser tabs. Actually, I was reproducing this with `mode: camera`, but also tried your static url and after dozen of tries reproduced it too. 

Note: it may require not just couple tries like I stated in 2nd step, but more(around 10) to reproduce.

Basic card config:
```
type: custom:frigate-card
cameras:
  - camera_entity: camera.svetaine_frigate
view:
  default: image
image:
  mode: camera
  refresh_seconds: 5
```
