### ISSUE TITLE
`go2rtc` provider is laggy/slow

### ISSUE THREAD

**Issue by ddanielww** [dermotduffy/frigate-hass-card#1671] opened 2024-11-04 13:47 UTC
Frigate working (Docker), integration with home assistant all setup (HA OS).

If I watch the streams in go2rtc they have fast and have audio.

When I add this to the card and select go2rtc as the provider its really laggy and no audio.

If I select webRTC card its live and with audio.

Why would the go2rtc option be slow with no audio when it works in the go2rtc interface?

**Comment by Klench** [comment] 2024-11-04 14:01
I experience something similar when my phone (iOS) is connected via Wi-Fi, but not on cellular. Not on PC though.
I think the issue is that for some reason, it is actually not previewing a go2rtc stream but jsmpeg instead.
Affects both Companion app and web page.

**Comment by ddanielww** [comment] 2024-11-04 14:03
I am viewing streams locally on edge.

I have tried both and windows.

**Comment by dermotduffy** [comment] 2024-11-06 16:13
@ddanielww In future, please do not ignore the templated fields for new issues. That information is necessary to help you and it costs more time for developers when you ignore them, this is why "PLEASE DO NOT IGNORE THIS TEMPLATE" is literally in the template. Thank you in advance.

Minimally please do this: On the card, hold down the Default/Frigate menu button for a few seconds then paste the diagnostics below. No help can be provided without this.

**Comment by clsferguson** [comment] 2024-11-22 18:00
I'm having a similar issue, should I start a new issue? or try to get this one sorted? additionally, I'm having some nabu casa streaming issues. I don't have go2rtc to watch the stream in. But in frigate the streams all play as mse too.

https://www.reddit.com/r/frigate_nvr/comments/1gwqoob/nabu_casa_and_frigate_in_a_docker_container_laggy/

locally, and through cloudflare tunnel, the behavior is the same. if I leave the go2rtc mode as "- mse" the frame rate is full frames. But if I only use "- webrtc" I only get about 1fps.

```
Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.11.3",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0",
  "date": "2024-11-22T17:55:03.169Z",
  "frigate_version": {
    "95d02a0efa42332dfb375b526e010897": "5.4.0/0.14.1-f4f3cfa"
  },
  "lang": "en",
  "timezone": "America/Denver",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "panel": true,
    "cameras": [
      {
        "camera_entity": "camera.front_1",
        "live_provider": "go2rtc",
        "id": "front_1_hd",
        "hide": true,
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ]
        }
      },
      {
        "camera_entity": "camera.doorbell",
        "live_provider": "go2rtc",
        "id": "doorbell_hd",
        "hide": true,
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ]
        }
      },
      {
        "camera_entity": "camera.driveway_cam",
        "live_provider": "go2rtc",
        "id": "driveway_cam_hd",
        "hide": true,
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ]
        }
      },
      {
        "camera_entity": "camera.garage",
        "live_provider": "go2rtc",
        "id": "garage_hd",
        "hide": true,
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ]
        }
      },
      {
        "camera_entity": "camera.rear_garage_1",
        "live_provider": "go2rtc",
        "id": "rear_garage_1_hd",
        "hide": true,
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ]
        }
      },
      {
        "camera_entity": "camera.shop",
        "live_provider": "go2rtc",
        "id": "shop_hd",
        "hide": true,
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ]
        }
      },
      {
        "camera_entity": "camera.shop_shed",
        "live_provider": "go2rtc",
        "id": "shop_shed_hd",
        "hide": true,
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ]
        }
      },
      {
        "camera_entity": "camera.front_1",
        "live_provider": "go2rtc",
        "id": "front_1_sub",
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ],
          "stream": "front_1_sub"
        },
        "dependencies": {
          "cameras": [
            "front_1_hd"
          ]
        }
      },
      {
        "camera_entity": "camera.doorbell",
        "live_provider": "go2rtc",
        "id": "doorbell_sub",
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ],
          "stream": "doorbell_sub"
        },
        "dependencies": {
          "cameras": [
            "doorbell_hd"
          ]
        }
      },
      {
        "camera_entity": "camera.driveway_cam",
        "live_provider": "go2rtc",
        "id": "driveway_cam_sub",
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ],
          "stream": "driveway_cam_sub"
        },
        "dependencies": {
          "cameras": [
            "driveway_cam_hd"
          ]
        }
      },
      {
        "camera_entity": "camera.garage",
        "live_provider": "go2rtc",
        "id": "garage_sub",
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ],
          "stream": "garage_sub"
        },
        "dependencies": {
          "cameras": [
            "garage_hd"
          ]
        }
      },
      {
        "camera_entity": "camera.rear_garage_1",
        "live_provider": "go2rtc",
        "id": "rear_garage_1_sub",
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ],
          "stream": "rear_garage_1_sub"
        },
        "dependencies": {
          "cameras": [
            "rear_garage_1_hd"
          ]
        }
      },
      {
        "camera_entity": "camera.shop",
        "live_provider": "go2rtc",
        "id": "shop_sub",
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ],
          "stream": "shop_sub"
        },
        "dependencies": {
          "cameras": [
            "shop_hd"
          ]
        }
      },
      {
        "camera_entity": "camera.shop_shed",
        "live_provider": "go2rtc",
        "id": "shop_shed_sub",
        "go2rtc": {
          "modes": [
            "webrtc",
            "mse"
          ],
          "stream": "shop_shed_sub"
        },
        "dependencies": {
          "cameras": [
            "shop_shed_hd"
          ]
        }
      }
    ],
    "menu": {
      "buttons": {
        "substreams": {
          "icon": "mdi:high-definition"
        },
        "microphone": {
          "enabled": true,
          "alignment": "opposing"
        }
      }
    }
  }
}
```

**Comment by dermotduffy** [comment] 2024-11-23 22:53
@clsferguson Please file a new issue. Thanks!

**Comment by dermotduffy** [comment] 2024-11-23 22:54
@ddanielww Closing this issue for now. Please open a new issue (with the templated content) if you'd like additional support. Thanks!

**Closed by dermotduffy** 2024-11-23 22:54 UTC
Labels: question
