### ISSUE TITLE
Ability to request specific clip or snapshot by using query string 

### ISSUE THREAD

**Issue by ronluna** [dermotduffy/frigate-hass-card#1309] opened 2023-10-26 09:37 UTC
Currently query string support calling the most recent clip or snapshot like this:

https://ha.mydomain.org/lovelace-test/0?frigate-card-action:main:clips

would it be possible to send the event's id to be able. to get the specific clip or snapshot of a camera ? maybe something like this ?

https://ha.mydomain.org/lovelace-test/0?frigate-card-action:main:clips:event_id 
https://ha.mydomain.org/lovelace-test/0?frigate-card-action:main:snapshot:event_id

**Comment by dermotduffy** [comment] 2023-10-27 01:11
I believe this is a duplicate of: https://github.com/dermotduffy/frigate-hass-card/issues/1246

**Closed by dermotduffy** 2023-10-27 01:11 UTC
