### ISSUE TITLE
Lot of error messages in js console - Safari

### ISSUE THREAD

**Issue by luzik** [dermotduffy/frigate-hass-card#465] opened 2022-03-14 06:47 UTC
I have two views with frigate card, switching between them always log into browser console

`WebSocket connection to 'ws://192.168.123.10:8123/api/frigate/frigate/jsmpeg/wejscie?authSig=XXX' failed: The operation couldn’t be completed. Socket is not connected`

Sometimes last sentence in error is `(kNWErrorDomainPOSIX error 96 - No message available on STREAM)`
My JSMpeg stream plays as usual. So the only issue is that it's spam log. Under Chromium there is no such issue

**Comment by dermotduffy** [comment] 2022-06-07 13:46
I used to be able to reproduce this, but since the JSMPEG player version was bumped (for the upcoming v4 build) I cannot. These errors are coming from deep within that library, so it may take quite a bit of hackery to mask them ... I'm going to close this for now, and we can revisit if you reliably reproduce this issue with the v4 build which will shortly be available.

**Closed by dermotduffy** 2022-06-07 13:46 UTC
Labels: bug
