### ISSUE TITLE
Language incorrectly chosen in certain circumstances?

### ISSUE THREAD

**Issue by mattfacer** [dermotduffy/frigate-hass-card#962] opened 2023-02-22 14:44 UTC
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

v4.0.0

**Browser and Operating System:**

Windows 10, Chrome

**Description of problem:**

Installing v4.0.0 from Hacs - when placing the card on the dashboard, the visual screen is all in Italian (I think!) 

![image](https://user-images.githubusercontent.com/338577/220656800-aeb3488d-f2d0-416a-a1d5-94911b1a4339.png)

**Comment by dermotduffy** [comment] 2023-02-23 17:05
The language comes from either...

(1) The selected language in the Home Assistant UI.

<img width="585" alt="Screen Shot 2023-02-23 at 9 00 54 AM" src="https://user-images.githubusercontent.com/1136829/220977466-b7223827-5462-4c9f-99f8-dcfe76273b0f.png">

(2) ... or if that is not specified, it falls back to whatever browser language(s) you have configured. Here's Chrome as an example:

<img width="859" alt="Screen Shot 2023-02-23 at 9 03 52 AM" src="https://user-images.githubusercontent.com/1136829/220978184-d9f7ee48-e413-41c4-9cdc-785fddb5cf9f.png">

If that still doesn't find a valid language, English will be the language.

Can you verify neither (1) nor (2) are somehow set surprisingly to Italian? ;-) Also hold down the Frigate menu button for a few seconds, and paste the diagnostics info here ...

**Comment by dermotduffy** [comment] 2023-02-23 17:22
BTW: Is it only the editor, or the whole card? (e.g. if you hover over a menu icon, is it in the expected language?)

**Comment by mattfacer** [comment] 2023-02-27 14:05
Hi - apologies for the late reply. In Settings > General, the launguage is "English".

![image](https://user-images.githubusercontent.com/338577/221583537-1c1146be-03fd-470f-906a-ba025a8bad6b.png)

I checked on Chrome - weirdly Italian is there. No idea why. I don't speak a word of it. 

![image](https://user-images.githubusercontent.com/338577/221583747-572ec2f6-1e8a-408c-a9b7-196a43c5e9c8.png)

Here's the output when I had Italian as a language option in Chrome

```
{
  "ha_version": "2023.2.5",
  "card_version": "4.0.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
  "date": "2023-02-27T14:03:54.334Z",
  "frigate_version": {
    "8adfd3529b534472d4366c77ab6e4c71": "3.0.1/0.10.1-83481af"
  },
  "lang": "it",
  "git": {
    "build_version": "4.0.0-HEAD+ge5a0bf4",
    "build_date": "Fri, 23 Sep 2022 00:27:16 GMT",
    "commit_date": "Thu, 22 Sep 2022 16:53:03 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.back_conservatory"
      }
    ]
  }
}
```

When I added the card and wasn't in edit mode, the icons were all in Italian too. I removed Italian, and sure enough the icons went back to english. 

I have refreshed the browser, and now the card config is back in English. Many thanks!

**Comment by dermotduffy** [comment] 2023-02-27 15:19
Excellent. I'll close this issue as this seems working as intended.

**Comment by felipecrs** [comment] 2023-02-27 15:56
@dermotduffy I just realized that I'm having the same behavior on https://github.com/dermotduffy/frigate-hass-card/issues/970#issue-1601450764.

As you can see, my HA is in portuguese, but the Frigate Hass Card settings page is in English.

**Comment by felipecrs** [comment] 2023-02-27 15:57
My browser is indeed in English, but my HA profile has PT-BR set as default (which is the one preferred for everything else in HA).

So, I guess the card should give priority to HA's user setting rather than browser's setting so that it matches the behavior of other components in HA?

**Comment by dermotduffy** [comment] 2023-02-28 02:14
@felipecrs That's exactly what it (tries to) do. The code is [very simple](https://github.com/dermotduffy/frigate-hass-card/blob/main/src/localize/localize.ts#L20). 

Would you mind opening a HA window, opening dev tools, run this in the console and tell me what you get:

```
JSON.parse(localStorage.getItem('selectedLanguage')).replace('-', '_')
```

It should show `pt_BR`.

**Comment by dermotduffy** [comment] 2023-02-28 02:16
Here's what I see if I set the HA language to Portuguese:

![editor](https://user-images.githubusercontent.com/1136829/221735655-efaab076-50ea-465e-81a6-84d2a7e28c40.png)

**Comment by felipecrs** [comment] 2023-02-28 03:14
I get:

```
Uncaught TypeError: Cannot read properties of null (reading 'replace')
    at <anonymous>:1:53
```

![image](https://user-images.githubusercontent.com/29582865/221744399-01b24ab7-4ceb-44af-8f98-7cf664444f30.png)

**Comment by felipecrs** [comment] 2023-02-28 03:16
https://user-images.githubusercontent.com/29582865/221744534-404e94d1-30c7-4c40-b89c-917c39b281b0.mp4

**Comment by dermotduffy** [comment] 2023-02-28 06:14
> I get:
> 
> ```
> Uncaught TypeError: Cannot read properties of null (reading 'replace')
>     at <anonymous>:1:53
> ```
> 
> ![image](https://user-images.githubusercontent.com/29582865/221744399-01b24ab7-4ceb-44af-8f98-7cf664444f30.png)

Huh. It's not saving the language for some reason (at least not saving it in the same place).

Very silly suggestion: Try changing it to any other language, the back to Portugese again, and see if it's in the `localStorage` then?

**Comment by felipecrs** [comment] 2023-02-28 13:08
It seems to work:

![image](https://user-images.githubusercontent.com/29582865/221863304-08faa95f-e5f3-4b8a-a81f-8dad3e96dde9.png)

Now the card picked up the right language. I'll check here if there is another HA API to get this language.

**Comment by felipecrs** [comment] 2023-02-28 13:13
Apparently it's also saved in the `hass` object: https://github.com/home-assistant/frontend/blob/dev/src/fake_data/provide_hass.ts#L221

Perhaps you can use it as fallback in case selectedLanguage returns nothing from localStorage.

**Comment by dermotduffy** [comment] 2023-03-04 21:17
@felipecrs Good idea -- but not easily, as `localize` intentionally does not use the `hass` object. This comes from this decision in the boilerplate card: https://github.com/custom-cards/boilerplate-card/issues/32 . Now we could just do differently here, but the same logic holds, this would require plumbing the hass object through to every single location a translation is required, which is a lot of locations ...

Not sure it's worth it. What do you think?

**Comment by felipecrs** [comment] 2023-03-04 21:52
I noticed that this issue apparently comes back every time I upgrade Home Assistant. It seems to delete the key from the browser storage, and switching the language again brings it back (i.e. not reliable at all), at least for me.

> Not sure it's worth it. What do you think?

Well, unless there is some other way to fix the issue. But in that case, we can somehow cache this information so that it is only discovered once.

**Comment by dermotduffy** [comment] 2023-03-04 22:44
> Well, unless there is some other way to fix the issue. But in that case, we can somehow cache this information so that it is only discovered once in the card's lifetime.

Yeah. I just did this. It means we won't ever "dynamically" change language, but that's not very likely anyway since the user will navigate to the HA language choice and then navigate back to the card (and it'll all work fine). Very slight performance win also.

**Closed by dermotduffy** 2023-03-04 22:44 UTC
Labels: question
