### ISSUE TITLE
Issue: Frigate clips are no longer playing in HA.  They work fine in the Frigate UI.

### ISSUE THREAD

**Issue by carda21** [dermotduffy/frigate-hass-card#1686] opened 2024-11-17 06:51 UTC
Not sure whats going on lately.  few gremlins creeping in.  clips aren't playing.  I just get a blank media screen.  nothing too relevant in the frigate logs except maybe a blank 400 error.

Have cleared my cache.  recording are on my NAS, as are snapshots etc.  Frigate UI has no issues.  Frigate and HA are containers on the same host.

Frigate config:

``` mqtt:
mqtt:
  enabled: true
  host: HOST
  port: 1883
  user: USER
  password: PASSWORD

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

ui:
  timezone: <TIMEZONE>

go2rtc:
  streams:
    drivewayptz:
      - rtsp://<IP_CAM>:554/Streaming/channels/101
    drivewayptz_detect:
      - rtsp://<IP_CAM>:554/Streaming/channels/102
    shed:
      - rtsp://<IP_CAM>/profile2/media.smp
    shed_detect:
      - rtsp://<IP_CAM>/profile4/media.smp
    shedoutsidedoor:
      - rtsp://<IP_CAM>/profile2/media.smp
    shedoutsidedoor_detect:
      - rtsp://<IP_CAM>/profile4/media.smp
    shedptz:
      - rtsp://<IP_CAM>/Streaming/Channels/01
    shedptz_detect:
      - rtsp://<IP_CAM>/Streaming/Channels/02
  webrtc:<IP_CAM>
    candidates:
      - <IP FRIGATE HOST>:8555
      - stun:8555

# auth:
#   reset_admin_password: True

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - motorcycle
    - cat
    - dog

review:
  # Optional: alerts configuration
  alerts:
    # Optional: labels that qualify as an alert (default: shown below)
    labels:
      - car
      - person
      - motorcycle

cameras:
  drivewayptz: # <------ Name the camera
    live:
      stream_name: drivewayptz
    onvif:
      host: XXX.XXX.XXX.XXX
      port: 80
      user: admin
      password: PASSWORD
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/drivewayptz_detect # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/drivewayptz
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      stationary:
        interval: 3600
        threshold: 360
    record:
      enabled: true
      retain:
        days: 21
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 30
    motion:
      mask:
        - 0.574,0.002,0.573,0.055,0.037,0.058,0.036,0
        - 0.582,0,0.584,0.264,0.632,0.427,0.682,0.584,0.816,0.595,1,0.622,1,0
        - 0.358,0.128,0.362,0.058,0,0.061,0,0.128
      threshold: 35
      contour_area: 10
      improve_contrast: 'true'
    zones:
      DrivewayMainZone:
        coordinates: 
          0.163,0.493,0.338,0.427,0.355,0.291,0.364,0.22,0.359,0.143,0.481,0.142,0.484,0.328,0.558,0.397,0.609,0.484,0.636,0.599,0.606,0.765,0.623,0.957,0.68,1,0,1,0,0.723
        inertia: 3
        loitering_time: 0
      DrivewaySecondaryZone:
        coordinates: 0.649,0.589,1,0.636,1,1,0.709,1,0.636,0.945,0.62,0.776,0.644,0.668
        inertia: 3
        loitering_time: 0
        objects:
          - cat
          - dog
          - person
    review:
      alerts:
        required_zones:
          - DrivewayMainZone
          - DrivewaySecondaryZone
      detections:
        required_zones:
          - DrivewayMainZone
          - DrivewaySecondaryZone
  shed:
    live:
      stream_name: shed
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/shed_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/shed
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      stationary:
        interval: 3600
        threshold: 360
    record:
      enabled: true
      retain:
        days: 21
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 30
    motion:
      mask: 0.246,0.071,0,0.072,0,0,0.248,0
    zones:
      ShedInsideMainZone:
        coordinates: 0,0.087,0.253,0.085,0.256,0,1,0,1,1,0,1
        loitering_time: 0
    review:
      alerts:
        required_zones: ShedInsideMainZone
      detections:
        required_zones: ShedInsideMainZone
  shedoutsidedoor:
    live:
      stream_name: shedoutsidedoor
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/shedoutsidedoor_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/shedoutsidedoor
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      stationary:
        interval: 3600
        threshold: 360
    record:
      enabled: true
      retain:
        days: 21
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 30
    motion:
      mask:
        - 0,0.136,0.397,0,0,0
        - 0.394,0.037,1,0.23,1,0,0.403,0
    zones:
      ShedOutsideMainZone:
        coordinates: 0.004,0.152,0.347,0.04,0.394,0.064,1,0.273,1,1,0,1
        loitering_time: 0
        objects: person
    review:
      alerts:
        required_zones: ShedOutsideMainZone
      detections:
        required_zones: ShedOutsideMainZone
  shedptz:
    live:
      stream_name: shedptz
    onvif:
      host: XXX.XXX.XXX.XXX
      port: 80
      user: admin
      password: PASSWORD
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/shedptz_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/shedptz
          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      stationary:
        interval: 3600
        threshold: 360
    record:
      enabled: true
      retain:
        days: 21
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    snapshots:
      enabled: true
      retain:
        default: 30

    motion:
      mask: 0,0,0,0.118,1,0.117,1,0
    zones:
      ShedPTZMainZone:
        coordinates: 0,0.132,0.608,0.128,1,0.331,1,1,0,1
        loitering_time: 0
    review:
      alerts:
        required_zones: ShedPTZMainZone
      detections:
        required_zones: ShedPTZMainZone
logger:
  default: info
version: 0.14

```Card diagnostics. Please review for confidential information prior to sharing
{
  "ha_version": "2024.11.2",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Linux; Android 14; SM-X916B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.107 Safari/537.36 Home Assistant/2024.10.3-14058 (Android 14; SM-X916B)",
  "date": "2024-11-17T06:40:47.324Z",
  "frigate_version": {
    "01JCS199ZVW1CTMCWAY4KMM2N9": "5.4.0/0.14.1-f4f3cfa"
  },
  "lang": "en",
  "timezone": "Australia/Melbourne",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.drivewayptz",
        "live_provider": "go2rtc",
        "go2rtc": {
          "stream": "drivewayptz"
        }
      },
      {
        "camera_entity": "camera.shed",
        "live_provider": "go2rtc",
        "go2rtc": {
          "stream": "shed"
        }
      },
      {
        "camera_entity": "camera.shedoutsidedoor",
        "live_provider": "go2rtc",
        "go2rtc": {
          "stream": "shedoutsidedoor"
        }
      },
      {
        "camera_entity": "camera.shedptz",
        "live_provider": "go2rtc",
        "go2rtc": {
          "stream": "shedptz"
        }
      }
    ],
    "elements": [
      {
        "type": "icon",
        "icon": "mdi:arrow-left",
        "style": {
          "bottom": "2%",
          "left": "4%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "pan": "LEFT",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "ContinuousMove"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:arrow-right",
        "style": {
          "bottom": "2%",
          "left": "12%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "pan": "RIGHT",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "ContinuousMove"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:arrow-up",
        "style": {
          "bottom": "2%",
          "left": "20%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "tilt": "UP",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "ContinuousMove"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:arrow-down",
        "style": {
          "bottom": "2%",
          "left": "28%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "tilt": "DOWN",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "ContinuousMove"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:magnify-plus-outline",
        "style": {
          "bottom": "2%",
          "left": "36%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "zoom": "ZOOM_IN",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "ContinuousMove"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:magnify-minus-outline",
        "style": {
          "bottom": "2%",
          "left": "44%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "zoom": "ZOOM_OUT",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "ContinuousMove"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:numeric-1-box-outline",
        "style": {
          "bottom": "2%",
          "left": "52%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "preset": "PTZPresetToken1001",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "GotoPreset"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:numeric-2-box-outline",
        "style": {
          "bottom": "2%",
          "left": "60%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "preset": "PTZPresetToken1002",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "GotoPreset"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:numeric-3-box-outline",
        "style": {
          "bottom": "2%",
          "left": "68%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "preset": "PTZPresetToken1003",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "GotoPreset"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:numeric-4-box-outline",
        "style": {
          "bottom": "2%",
          "left": "76%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "preset": "PTZPresetToken1004",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "GotoPreset"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:numeric-5-box-outline",
        "style": {
          "bottom": "2%",
          "left": "84%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "preset": "PTZPresetToken1005",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "GotoPreset"
          }
        }
      },
      {
        "type": "icon",
        "icon": "mdi:numeric-6-box-outline",
        "style": {
          "bottom": "2%",
          "left": "92%",
          "color": "white",
          "opacity": "40%",
          "background-color": "black",
          "transform": "scale(1.5, 1.5)"
        },
        "tap_action": {
          "action": "call-service",
          "service": "onvif.ptz",
          "service_data": {
            "entity_id": "all",
            "preset": "PTZPresetToken1006",
            "speed": 1,
            "distance": 0.3,
            "move_mode": "GotoPreset"
          }
        }
      }
    ],
    "live": {
      "preload": false
    }
  }
}

**Comment by kingp0dd** [comment] 2024-11-17 10:33
I get this error too:

`Failed to start WebRTC stream: webrtc: streams: exec/rtsp [rtsp @ 0x7fea57ed0000] method DESCRIBE failed: 404 Not Found [in#0 @ 0x7fea58212c00] Error opening input: Server returned 404 Not Found Error opening input file rtsp://127.0.0.1:18554/camera.10_10_20_2?audio&source=ffmpeg:camera.10_10_20_2%23audio%3Dopus%23query%3Dlog_level%3Ddebug&log_level=debug. Error opening input files: Server returned 404 Not Found (camera.10_10_20_2). [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).`

**Comment by dermotduffy** [comment] 2024-11-17 17:38
Known Home Assistant bug: Duplicate of #1678

**Closed by dermotduffy** 2024-11-17 17:38 UTC
