### ISSUE TITLE
Live view freezes and jerks with Reolink

### ISSUE THREAD

**Issue by copa80** [dermotduffy/frigate-hass-card#1745] opened 2024-12-12 12:09 UTC
Since 6.0.0 release the live view does Not work. It stucks freeze and jerks. 10 cameras all the same. Worked brilliant before.

**Checklist:**

- Please try updating to the [latest available version](https://github.com/dermotduffy/frigate-hass-card/releases).
- Please try clearing your browser cache.

**[REQUIRED] Card diagnostic information:**

```yaml

```

**[REQUIRED] Description of problem:**

**[OPTIONAL] Last working release (if known):**

**[OPTIONAL] Javascript errors shown in the web inspector:**

```text

```

**[OPTIONAL] Additional information:**

**Comment by Gamso** [comment] 2024-12-12 17:42
@copa80 Can you confirm that it's the same problem as this issue #1741 ?

**Comment by copa80** [comment] 2024-12-12 17:56
> @copa80 Can you confirm that it's the same problem as this issue #1741 ?
Yes seems to be the same

**Comment by dermotduffy** [comment] 2024-12-13 03:47
Closing as duplicate of #1741

**Closed by dermotduffy** 2024-12-13 03:47 UTC
Labels: bug
