### ISSUE TITLE
Frigate backend is falling over due to event requests from v5 card

### ISSUE THREAD

**Issue by HHUBSS** [dermotduffy/frigate-hass-card#1132] opened 2023-05-01 05:38 UTC
I got this again after updating Frigate (server and card) to latest. Before I migrate, my retention is 60. I change it to 50 days but still an error.

This is the issue before but it was resolved so I change back to 60 days of retention >> https://github.com/dermotduffy/frigate-hass-card/issues/911

![7](https://user-images.githubusercontent.com/89816305/235411428-ddb41734-98ef-4476-a9ab-43eb6777c731.jpg)

Frigate log:
![9](https://user-images.githubusercontent.com/89816305/235412082-056e92f9-05d7-49ff-919a-c2e38886ba7f.png)

This is what I got in Home assistant log

![8](https://user-images.githubusercontent.com/89816305/235411581-5df5ab45-6875-4d80-b486-bad335ea55d1.jpg)

**Comment by dermotduffy** [comment] 2023-05-01 14:41
Just like #911 , the issue is your Frigate backend appears to be falling over. There's only so much the card can do, so I think you're going to have to take this for discussion to the [backend repo](https://github.com/blakeblackshear/frigate). 

First though, lets make the smallest possible replication case and make sure the card is not spamming the backend inappropriately. Can you get this to happen on initial load? It will be easier if so.

Temporarily add this to your card config:

```yaml
debug:
  logging: true
```
Then open your Javascript console (F12 in Chrome), then reload. You'll see a bunch of debugging statements from the Frigate card. For the lines labeled "CameraManager request" expand the little arrow next to the "Queries" so it shows what the query is:
 
![debug](https://user-images.githubusercontent.com/1136829/235468715-e8c6a26b-cd82-49e7-9900-22293110d3ae.png)

[In this example, you can see my card is making two event queries -- one for timeline, one for thumbnails -- and one recording segments query]

Screenshot what you see and paste it back here. If the card was spamming your backend, we'd see the requests show up here.

**Comment by HHUBSS** [comment] 2023-05-01 17:30
Thank you. The frigate card does not get any more retrieve errors for more than 10 hours after I restart my system, the unraid server. I don't want to restart anymore the Frigate server by adding the code you gave. I will, however, test that and add the code when it happens again.

**Comment by dermotduffy** [comment] 2023-05-02 02:16
> I don't want to restart anymore the Frigate docker container by adding the code you gave.

The yaml provided is for the card, not the server.

As a side note if you only see this behavior when you restart Frigate, that's actually completely normal & expected.

> I will, however, test that and add the code when it happens again.

For now, I'll close this bug as I don't think this is anything related to the card (but rather either underpowered hardware, or something on the backend side). Next time this happens, if you discover evidence that the card is the issue (e.g. spamming the backend), definitely re-open it here -- otherwise reopen it on the Frigate repo side.

Thanks and good luck!

**Closed by dermotduffy** 2023-05-02 02:16 UTC

**Comment by raelbsd** [comment] 2023-05-02 19:26
Hi! I was following this issue because it's happening something similar since last week. The card was working perfect (great job, thanks!) for months, but now I'm facing this error:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/12398295/235763996-35bf8c86-ca5d-44c7-83e5-1cf14583795e.png">
The error ends with an invalid keys message. I've add the debug part to a dashboard containing only 1 card, I didn't see the CameraManager request part in the javascript console, this is my output:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/12398295/235765315-ee4e786f-6167-4536-bd64-3a2a1ec18292.png">
I'm not sure if it's the same error, I'll like to getting this back to work. Maybe you can shed some light on this.
Thanks!

**Comment by raelbsd** [comment] 2023-05-02 20:20
Just in case this is how I've added the debug part on the dashboard. I've fixed the 404 error I had (an old resource I've deleted), but the frigate card throws the same.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/12398295/235774987-ec8718c6-1c87-41aa-a754-3e9f1a978655.png">

**Comment by dermotduffy** [comment] 2023-05-03 02:22
@raelbsd This is definitely not the same issue. Lets keep it one topic per issue, so I've opened a new one and we can discuss there. Thanks!
