### ISSUE TITLE
"auto camera audio feed unmute" when enabling 2 way audio microphone 

### ISSUE THREAD

**Issue by TheBlueKingLP** [dermotduffy/frigate-hass-card#1236] opened 2023-07-28 19:39 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I forgot to unmute audio feed when trying to use 2 way audio

**Describe the solution you'd like**
Add an option to enable "auto camera audio feed unmute" when enabling 2 way audio microphone 

**Describe alternatives you've considered**
Manually enabling audio as well

**Comment by dermotduffy** [comment] 2023-07-29 14:56
I think this is a duplicate of: https://github.com/dermotduffy/frigate-hass-card/issues/1130

Please re-open if I'm reading it wrong, thanks for the feature request!

**Closed by dermotduffy** 2023-07-29 14:56 UTC
