### ISSUE TITLE
Clips and Snapshots not loading

### ISSUE THREAD

**Issue by loadamasta** [dermotduffy/frigate-hass-card#1678] opened 2024-11-07 15:16 UTC
Since HA 2024.10.4 (maybe a version earlier) the card does no longer load the clips and snapshots. 

The thumbnails however are all there and show up as usual. However, after a clip on the thumbnail the clip or snapshot is not loading.

Issue occurs on Microsoft Edge (Windows), Firefox (Windows), Safari (macos), companion app (iOS).

![image](https://github.com/user-attachments/assets/e678ff3a-3615-4895-a3ef-02fc7b42eb4b)

**Comment by francescopeloi** [comment] 2024-11-07 15:20
Happening to me too, I don't see any error on the console. I tried with the previous HA version, working fine, reloaded the new UI, broken. Some on android app. The new HA has a change about WebRTC.

**Comment by bazzio68** [comment] 2024-11-07 15:43
Same problem here, no live view.. but audio of cam is working

**Comment by meliborn** [comment] 2024-11-07 17:03
same for me, I see pictures of clips but I can't load them.

<img width="490" alt="Снимок экрана 2024-11-07 в 20 03 01" src="https://github.com/user-attachments/assets/5fb8fab2-ec77-46f2-9152-401e0bee8afa">

**Comment by jeffreyrdubois** [comment] 2024-11-07 21:55
Same issue for me as well

**Comment by IsaacInsoll** [comment] 2024-11-08 11:58
Same here

**Comment by TheDuffman85** [comment] 2024-11-08 12:34
I can conform this is also an issue on v6.0.0-beta.8

**Comment by Eft-Newt** [comment] 2024-11-08 12:46
Similar. Clips and recordings won't load. Snapshots do load for me. Browser doesn't seem to matter. Android webview (via the Wallpanel app), Firefox in Windows 11 or Ubuntu 22.04,
I'll post this from Home Assistant Logs... not sure if this is relevant to this issue. I don't believe I have independently installed go2rtc installed on HA.

06:40:25.330 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:230 > error="write tcp 127.0.0.1:18554->127.0.0.1:43930: write: broken pipe"
06:40:35.656 WRN [rtsp] error="streams: exec/rtsp\n[in#0 @ 0x7fe330812c00] Error opening input: Invalid data found when processing input\nError opening input file rtsp://127.0.0.1:18554/camera.birdseye?audio.\nError opening input files: Invalid data found when processing input\n" stream=camera.birdseye
06:40:35.656 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:230 > error="write tcp 127.0.0.1:18554->127.0.0.1:53266: write: broken pipe"
06:40:40.815 WRN [rtsp] error="streams: exec/rtsp\n[in#0 @ 0x7f3d86212c00] Error opening input: Invalid data found when processing input\nError opening input file rtsp://127.0.0.1:18554/camera.birdseye?audio.\nError opening input files: Invalid data found when processing input\n" stream=camera.birdseye
06:40:40.815 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:230 > error="write tcp 127.0.0.1:18554->127.0.0.1:53270: write: broken pipe"

Home Assistant details:
Core 2024.11.0, Supervisor 2024.11.2, Operating System 13.2, Frontend 20241106.0
Peace guys. Things have been going smooth for many months. Thank you for the projects.

**Comment by napper306** [comment] 2024-11-08 12:49
Similar. Clips and recordings won't load. Snapshots do load for me. Browser doesn't seem to matter. Android webview (via the Wallpanel app), Firefox in Windows 11 or Ubuntu 22.04,
I'll post this from Home Assistant Logs... not sure if this is relevant to this issue. I don't believe I have independently installed go2rtc installed on HA.

06:40:25.330 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:230 > error="write tcp 127.0.0.1:18554->127.0.0.1:43930: write: broken pipe"
06:40:35.656 WRN [rtsp] error="streams: exec/rtsp\n[in#0 @ 0x7fe330812c00] Error opening input: Invalid data found when processing input\nError opening input file rtsp://127.0.0.1:18554/camera.birdseye?audio.\nError opening input files: Invalid data found when processing input\n" stream=camera.birdseye
06:40:35.656 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:230 > error="write tcp 127.0.0.1:18554->127.0.0.1:53266: write: broken pipe"
06:40:40.815 WRN [rtsp] error="streams: exec/rtsp\n[in#0 @ 0x7f3d86212c00] Error opening input: Invalid data found when processing input\nError opening input file rtsp://127.0.0.1:18554/camera.birdseye?audio.\nError opening input files: Invalid data found when processing input\n" stream=camera.birdseye
06:40:40.815 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:230 > error="write tcp 127.0.0.1:18554->127.0.0.1:53270: write: broken pipe"

Home Assistant details:
Core 2024.11.0, Supervisor 2024.11.2, Operating System 13.2, Frontend 20241106.0

Until now things have been running smooth for many months. Thank you for the projects.

**Comment by Hukuma1** [comment] 2024-11-08 14:55
+1. I thought this was due to my new network and ports being blocked. Guess not!

**Comment by dermotduffy** [comment] 2024-11-08 15:19
Thank you all. I will investigate this weekend. If one of you that has this problem could hold down the Frigate menu button in the card for a few seconds, and then paste the diagnostics, that would be great.

**Comment by francescopeloi** [comment] 2024-11-08 15:32
```
{
  "ha_version": "2024.11.0",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
  "date": "2024-11-08T15:30:47.445Z",
  "frigate_version": {
    "3f32dde608d9d2653462afcc83306c6e": "5.4.0/0.14.1-f4f3cfa"
  },
  "lang": "en",
  "timezone": "Europe/Vatican",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.ingresso_civico_55",
        "go2rtc": {
          "modes": [
            "mse"
          ],
          "stream": "ingresso-civico-55-sub"
        },
        "live_provider": "auto"
      }
    ]
  }
}

**Comment by dermotduffy** [comment] 2024-11-08 15:37
Can reproduce. I think there is actually a tangle of 3 different issues here, all with the same symptoms:

* Issue 1: With HA 2024.11 clips don't appear to work (regardless of card or Frigate version)
* Issue 2: With any version of HA, but Frigate Integration version `v5.4.1` clips appear to return forbidden. This is almost certainly related to (my) https://github.com/blakeblackshear/frigate-hass-integration/pull/758 .
* Issue 3: With any version of HA, but Frigate `0.15+` clips don't appear to work ([issue](https://github.com/dermotduffy/frigate-hass-card/issues/1668), did not test myself)

I plan to address them in this order.

**Comment by dermotduffy** [comment] 2024-11-09 01:57
There's actually an issue 0 that has to be fixed first, not related to the card at all: https://github.com/blakeblackshear/frigate-hass-integration/issues/757

Until Frigate + HA works (without the card), no point in trying to fix the card.

This is an impressive tangled web of related issues!

**Comment by dermotduffy** [comment] 2024-11-09 22:56
* **Issue 0**: I believe I have traced this down to a Home Assistant frontend bug, follow that issue here: https://github.com/blakeblackshear/frigate-hass-integration/issues/757
* **Issue 1**: I need 0 fixed first to test, but I'll definitely need to make some card changes, at least these: https://github.com/dermotduffy/frigate-hass-card/pull/1679 . I plan to keep that PR open until 0 is resolved so I can know for sure.

**Comment by remon1496** [comment] 2024-11-10 01:18
Just an FYI. They’re also not playing trough the Media Browser in HA. Not sure if its related. Snapshots load, but recordings (and clips) never load. Just like in the card itself.

**Comment by dermotduffy** [comment] 2024-11-10 01:21
Yes, that is "Issue 0" described above. That must be fixed first in Home Assistant itself.

**Comment by macthaidhg** [comment] 2024-11-10 09:19
Clips were not working for me after HA 2024.11.1 update and frigate v0.15 beta. Rolling back to HA 2024.10.4 fixed it for me. I didn't have to roll back to frigate v0.14. Hope this helps!

**Comment by MilesTEG1** [comment] 2024-11-10 18:32
Se problem for me too.
Following this issue.

**Comment by Jurgonh** [comment] 2024-11-10 18:39
+1

**Comment by wr420** [comment] 2024-11-15 01:49
> +1. I thought this was due to my new network and ports being blocked. Guess not!

lol same, just switched to local ISP to Comcast and KNEW they were the problem :)

**Comment by Mikescotland** [comment] 2024-11-17 16:19
> I don't know if this is related, as I don't use frigate between the cams and HA, but after 24.11 a camera feed can mess up other things on the HA dash. Everything works fine until you ho to a tab with one or more camera feeds. After that this will happen
> 
> 1. If you are editing dash, gui for edit cards will come up blank, with just the header.
 (...)

Unrelated to frigate. You use a stream from Tuya servers.
Take a look here:
https://github.com/home-assistant/core/issues/94004

**Comment by hiteshsharma** [comment] 2024-11-19 15:12
@dermotduffy is there an issue open in HA for issue 0? I didn’t find on this thread. If not then I can open one

**Comment by dermotduffy** [comment] 2024-11-19 15:48
@hiteshsharma https://github.com/home-assistant/frontend/issues/22755 (fixed as of yesterday, presumably in next release)

**Comment by dermotduffy** [comment] 2024-11-19 15:50
Referring back to the [list of issues](https://github.com/dermotduffy/frigate-hass-card/issues/1678#issuecomment-2466489875) that I think are necessary to close this bug:

- **Issue 0**: This is now fixed (but not released).
- **Issue 1**: <-- I will work on this next.
- **Issue 2**: I will test this when 1 is fixed.

**Comment by bazzio68** [comment] 2024-11-22 20:10
> > @hiteshsharma [home-assistant/frontend#22755](https://github.com/home-assistant/frontend/issues/22755) (fixed as of yesterday, presumably in next release)
> 
> Unfortunately this fix didn't made it to the 2024.11.3 release. It still uses the 20241106.2 Frontend.

That's so ridiculously...

**Comment by jknoflook** [comment] 2024-11-24 02:07
This needs to have priority added to it. It's been too long.

**Comment by dermotduffy** [comment] 2024-11-28 04:31
Quick update summary for those playing along:

- **Issue 0**: This is now fixed in HA core, but as per the frustration in this thread, sadly the November releases didn't include it. There's a [pre-release v2024.12.0b0](https://github.com/home-assistant/core/releases/tag/2024.12.0b0) with the fix.
- **Issue 1**: This is now fixed, but needs a card release. I'll do that shortly, a little before the `2024.12` release goes live as it's not backwards compatible.
- **Issue 2**: As @macthaidhg said, I think this actually works fine and I have Frigate `0.15`, with HA `2024.12.0b0` working just fine with the card.

**Comment by EFG-TheDevopsGuy** [comment] 2024-11-28 11:21
So i can confirm it's working now with this docker image:
`image: 'homeassistant/home-assistant:2024.12.0b0'`

**Comment by francescopeloi** [comment] 2024-12-04 20:12
[HA core 2024.12.0](https://github.com/home-assistant/core/releases/tag/2024.12.0) is out, with the [HA front end (20241127.4)](https://github.com/home-assistant/frontend/releases/tag/20241127.4) that has the fix. I've just upgraded and everything is back working now. Thanks!

**Comment by IsaacInsoll** [comment] 2024-12-04 20:13
Thanks for letting us know 🔥

**Comment by dermotduffy** [comment] 2024-12-05 05:05
Excellent! OK, I'm going to consider this fixed for now. HA `2024.11` was certainly an adventure -- thanks to everyone for all the patience as we figured this out.

**Closed by dermotduffy** 2024-12-05 05:05 UTC
Labels: bug

**Comment by hiteshsharma** [comment] 2024-12-05 06:51
Still not fixed for me. Not sure if I'm missing something. Now the clips
are playing in HA media browser but not in the frigate card. No JS error.
I'm on following versions

HA Core: 2024.12.0
HA Supervisor: 2024.11.4
Frontend: 20241106.2
Frigate HA integration: 5.5.1
Frigate card: 6.0.0-beta.9

When I open the URL in <frigate-card-ha-hls-player> element, in a new tab,
the video loads.

Thanks in advance

**Comment by hiteshsharma** [comment] 2024-12-05 06:54
I reverted frigate card to beta 8 and clips play now. May be beta 9 is
introducing some new bug.

**Comment by francescopeloi** [comment] 2024-12-05 07:11
> HA Core: 2024.12.0
> HA Supervisor: 2024.11.4
> Frontend: 20241106.2
> Frigate HA integration: 5.5.1
> Frigate card: 6.0.0-beta.9

are you sure about the front end version? core 2024.12.0 comes with front end 20241127.4

**Comment by hiteshsharma** [comment] 2024-12-05 08:11
That’s what HA shows me

**Comment by TheDuffman85** [comment] 2024-12-05 08:14
This happens if the front end is still cached and you to not refresh. In this case the old front end with the bug is still used.

**Comment by dermotduffy** [comment] 2024-12-05 14:59
> This happens if the front end is still cached and you do not refresh. In this case the old front end with the bug is still used.

+1, the old frontend code is almost certainly still being used. Try clearing your cache.

Due to the high volume of people on this thread, I'm going to lock it to avoid spam. If anyone is still having problems and wishes to discuss, lets open a new issue and pick it up there. Thanks!
