### ISSUE TITLE
Any ideas how to get the iOS HA app to prompt me for microphone permissions?

### ISSUE THREAD

**Issue by asafalfa** [dermotduffy/frigate-hass-card#1255] opened 2023-08-26 19:47 UTC
Hey there,
quick question, Everything operates properly I am able to receive video and two-way audio, and I can answer and end calls via a web browser. (utilizing a frigate card with go2rtc)

But when I attempt the same via my iPhone, I can only listen but not speak.
In Settings → Home Assistant, there is no toggle option for the microphone, so I assume it is disabled.

any idea guys?

It works on android as well ! and also im my computer !
But not in the iphone web or HA...

**Comment by asafalfa** [comment] 2023-08-28 06:02
Guys? Anyone? Is this a Bug?
I don't understand why the Microphone is not prompt when I turn it on on Frigate card on the iPhone but on Android it works.?

**Comment by dermotduffy** [comment] 2023-08-28 14:33
@asafalfa I don't have an iOS device, so never tested this (but there's certainly nothing Android specific in the code). Have you tried in Safari vs the Home Assistant App? Is it possible you previously denied access to the microphone in the App?

**Comment by asafalfa** [comment] 2023-08-28 22:19
So I attempted this via Safari with the same outcomes as the Home assistant App...
I attempted to deactivate the home assistant to confirm that I had denied access, but to no avail.
I also attempted the same on three other iPhones, and they all behaved identically.

I believe this is a problem that no one has reported thus far, which I find odd:
now im kind blocked and have no idea what i can do about it :/ 
any suggestion?

**Comment by dermotduffy** [comment] 2023-08-29 02:33
> Any suggestion?

Afraid not, unless you are a developer who can debug yourself. Otherwise we can leave this issue open for a few weeks and see if someone else has the problem. Worst case I can try to test this in browserstack and see if I can reproduce.

**Comment by asafalfa** [comment] 2023-08-29 07:06
Sound good - much appricate !

**Comment by asafalfa** [comment] 2023-08-31 15:51
*** update
iOS via Safari + zero trust WORKS!
iOS via Home assistant + Zero trust - Not work ---- so this is something with the Home Assistant App on iOS…
iOS via Chrome + Zero trust - Not work

**Comment by dermotduffy** [comment] 2023-09-01 02:40
@asafalfa When you say "zero trust", what are you referring to?

**Comment by asafalfa** [comment] 2023-09-01 11:44
@dermotduffy Solution that came from cloudflare create tunnel from my computer to them ... which gives me the ability to connect without open any port, and does not require Nginx or ssl connection.

**Comment by asafalfa** [comment] 2023-09-01 13:21
ok updates !
https configured in the Home Assistant fixed it all - Mic is enabled !

**Comment by asafalfa** [comment] 2023-09-01 14:41
@dermotduffy  you will laugh at me, so in the HA app i configured the external with http - which worked but for us to get the Microphone you have to log in via HTTPS only ... and that fix the problem:)

No i just breaking my head how to set the intenal URL also with HTTPS since right now it regular http - Not sure how to do that:).

**Comment by dermotduffy** [comment] 2023-09-01 14:48
> @dermotduffy you will laugh at me, so in the HA app i configured the external with http - which worked but for us to get the Microphone you have to log in via HTTPS only ... and that fix the problem:)

Oh, heh, okay. I'll close this issue then.

> No i just breaking my head how to set the intenal URL also with HTTPS since right now it regular http - Not sure how to do that:).

I'm not quite following why you cannot just set the URL in the app to `https`, since you can enter the address manually, but I'm probably missing something. [This page might be relevant to your interests](https://companion.home-assistant.io/docs/troubleshooting/networking/).

**Closed by dermotduffy** 2023-09-01 14:48 UTC
Labels: question
