### ISSUE TITLE
WEBRTC Option - No auto mute

### ISSUE THREAD

**Issue by ddanielww** [dermotduffy/frigate-hass-card#1672] opened 2024-11-04 17:38 UTC
The webrtc card works better then the go2rtc option for me (go2rtc does not play well on mobile, no audio etc).

The webrtc card is great, however, it plays audio by default, anyway for this to be muted by default on live streams?

**Comment by ddanielww** [comment] 2024-11-04 17:56
muted: true
hide the mode option would be nice
style: '.mode {display: none}'
https://github.com/AlexxIT/WebRTC
Available in the card so just need to add to the frigate card somehow ?

**Comment by doctorkb** [comment] 2024-11-04 18:14
Duplicate of #1654

**Comment by ddanielww** [comment] 2024-11-04 19:08
can the audio and removing mode be implemented for the webrtc card?

Happy to provide logs etc but it's super easy to replicate

Start stream muted.
muted: true

hide the mode option would be nice as it gets in the way of the mute button on mobile.
style: '.mode {display: none}'

https://github.com/AlexxIT/WebRTC

**Comment by doctorkb** [comment] 2024-11-04 19:24
This card configuration is auto-muting for me on the latest Frigate Card beta:
`type: custom:frigate-card
cameras:
  - camera_entity: camera.backyard
    webrtc_card:
      entity: camera.backyard
    triggers:
      occupancy: false
    go2rtc:
      modes:
        - webrtc
    live_provider: webrtc-card
    title: Back Yard
menu:
  buttons:
    frigate:
      enabled: false
    cameras:
      enabled: false
    substreams:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    fullscreen:
      enabled: false
    timeline:
      enabled: false
    expand:
      enabled: true
    media_player:
      enabled: false
    microphone:
      enabled: true
    mute:
      enabled: true
    screenshot:
      enabled: true
  style: hover
  alignment: right
  position: bottom
live:
  draggable: false
  zoomable: false
  lazy_load: false
  show_image_during_load: true
  controls:
    builtin: false
  microphone:
    mute_after_microphone_mute_seconds: 1
    disconnect_seconds: 1
  auto_mute:
    - microphone
  display:
    mode: single
view:
  default: live
  camera_select: live
  dark_mode: "off"
timeline:
  show_recordings: false
performance:
  style:
    border_radius: false
    box_shadow: false
dimensions:
  aspect_ratio_mode: dynamic
status_bar:
  style: none
`

**Comment by ddanielww** [comment] 2024-11-04 19:48
**Default to unmuted / audio enabled.**

type: custom:frigate-card
cameras:
  - camera_entity: camera.camera1
    go2rtc:
      modes:
        - webrtc
    live_provider: webrtc-card


**Defaults to muted**

type: custom:frigate-card
cameras:
  - camera_entity:  camera.camera1
    go2rtc:
      modes:
        - webrtc
    live_provider: go2rtc

This is super easy to replicate, it is because the webrtc card defaults to unmute.

https://github.com/AlexxIT/WebRTC

We need a way to send parameters to the card as shown below.

Start stream muted.

muted: true

hide the mode option would be nice as it gets in the way of the mute button on mobile.

style: '.mode {display: none}'

**Comment by doctorkb** [comment] 2024-11-04 20:02
Try what I posted. It uses the webrtc card and loads muted. You may need to update your frigate-hass-card to a beta version.

Also, as I noted, this is a duplicate report of another issue. Tradition says you use the oldest open issue to discuss to keep it in one place.

**Comment by ddanielww** [comment] 2024-11-04 20:44
Okay this works...

The key is not to use the built-in controls and add these to the frigate menu.

I think people that are reporting this are using the inbuilt controls.

I am happy with this now.

or if you are using the build in controls add

type: custom:frigate-card
cameras:
  - camera_entity: camera.camera
    webrtc_card:
      entity: camera.simba_2
      style: '.mode {display: none}'     < removes mode 
      muted: true. < defaults to muted

**Comment by dermotduffy** [comment] 2024-11-10 00:45
See duplicate: https://github.com/dermotduffy/frigate-hass-card/issues/1654

**Closed by dermotduffy** 2024-11-10 00:45 UTC
Labels: bug
