### ISSUE TITLE
Add arbitrary date selection (to/from) in media filter

### ISSUE THREAD

**Issue by ronluna** [dermotduffy/frigate-hass-card#1319] opened 2023-11-06 21:27 UTC
It seems obvious although I'm not sure if it has not been implemented yet or I just can't find but I'm wondering if 
A date picker can be added to the media filter tray to allow a time range selection (From "date" to "date") ?

I know there is a date picker from the timeline view but it does not work on iOS device and can only be accessed from within the timeline screen. 

would be very helpful to improve performance and to search for very old events on specific dates.

**Comment by dermotduffy** [comment] 2023-11-06 22:00
> I'm not sure if it has not been implemented yet 

Correct! The media filter as implemented will currently let you choose a month-year combo, but not arbitrary dates.

**Comment by dermotduffy** [comment] 2024-02-04 20:17
Closing this as a duplicate of: https://github.com/dermotduffy/frigate-hass-card/issues/1224

**Closed** 2024-02-04 20:18 UTC
Labels: enhancement
