### ISSUE TITLE
Custom Element doesn't exist: frigate-card.

### ISSUE THREAD

**Issue by yannpub** [dermotduffy/frigate-hass-card#505] opened 2022-04-07 13:32 UTC
**Checklist:**
- [ X] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
I don't have the cards appearing in my iOS app on iPad. iOS is version 12.5.5

**Last working release (if known):**
Was working fine before

**Browser and Operating System:**
iOS 12.5.5, home assistant app or through iOS safari browser.
Frigate NVR is V3.1
HomeAssistant is 2022.3.8

**Description of problem:**
On my iPad device, running iOS 12.5.5, the card is not displayed, I have the error message below. (Reset FrontEnd Cache has been done properly)
On my phone, iOS15.4.1 is fine, I have my 2 cards getting properly displayed
On my desktop, it is working fine also, no issue either on displaying the card

![610B5FBF-1921-4D00-9DE2-04B9E7FD9106_1_201_a](https://user-images.githubusercontent.com/21988643/162209707-4e3e8c92-6843-4306-8c35-6f7bf4bf9863.jpeg)

**Comment by dermotduffy** [comment] 2022-04-08 02:38
Hmm. Maybe this is the same as https://github.com/dermotduffy/frigate-hass-card/issues/485 ? A way to test would be to try v3.0.0-rc.1 (https://github.com/dermotduffy/frigate-hass-card/releases/tag/v3.0.0-rc.1), then [reset your cache](https://github.com/dermotduffy/frigate-hass-card#home-assistant-ios-app-not-updating-after-card-version-change) and see if the card shows up -- the move forward to the latest version, re-reset the cache and see if it vanishes again ...

**Comment by yannpub** [comment] 2022-04-08 10:02
You are right, it is working on iOS12 with the RC1 version. Getting back to the latest card version brings the issue back. So effectively, it seems the issue might be similar to #485 .

**Comment by dermotduffy** [comment] 2022-04-09 00:34
OK -- lets carry on the investigation over the #485 then, and I'll close this one out. Thanks for testing!

**Closed by dermotduffy** 2022-04-09 00:34 UTC
Labels: bug

**Comment by Ramias1** [comment] 2022-10-21 17:59
Also getting this on an old iPad mini running 12.5.6.  V 4 of the frigate card and Home Assistant 2022.10.5.  @yannpub did you ever get this working on your old iPad?

**Comment by yannpub** [comment] 2022-10-21 20:52
@Ramias1 Unfortunately not. I was hoping the release 4 would solve the issue, but that was not the case :-(

**Comment by superdong69** [comment] 2022-12-18 02:18
Can we get this resolved please???

**Comment by dermotduffy** [comment] 2022-12-18 02:44
@superdong69 This card is developed and maintained purely as a hobby. Sadly there's quite an issue list for me to prioritize, I have limited hobby time and as this likely only effects people using devices with older webview libraries, resolving it is not a priority for me at this time. If you'd like to investigate and submit a PR, I would **love** it!

In the meantime, to make this more actionable, if someone could get and paste the Javascript console logs (which likely would contain a clue as to which function is the issue), that would be hugely helpful. Since I do not have an impacted device, I cannot do anything even if I had the time to investigate further myself.

**Comment by superdong69** [comment] 2022-12-18 02:49
> @superdong69 This card is developed and maintained purely as a hobby. Sadly there's quite an issue list for me to prioritize, I have limited hobby time and as this likely only effects people using devices with older webview libraries, resolving it is not a priority for me at this time. If you'd like to investigate and submit a PR, I would **love** it!
> 
> In the meantime, to make this more actionable, if someone could get and paste the Javascript console logs (which likely would contain a clue as to which function is the issue), that would be hugely helpful. Since I do not have an impacted device, I cannot do anything even if I had the time to investigate further myself.

I don't know much about programming, but I'd be glad to help if you told me where I could get that info for ya!

**Comment by yannpub** [comment] 2023-01-02 14:28
@dermotduffy I am not sure this is what you are looking for, is that the error message you were looking for from the console? 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/21988643/210244516-a272251c-3a3d-4b90-8da5-bd76cf70e7fa.png">

**Comment by dermotduffy** [comment] 2023-01-02 17:47
@yannpub Yes! Was there a file and line number to the right of those messages?

**Comment by yannpub** [comment] 2023-01-04 10:25
> @yannpub Yes! Was there a file and line number to the right of those messages?

Unfortunately not in Safari Console :-(

**Comment by hardwareadictos** [comment] 2023-02-13 12:11
Hey! I can confirm that the issue also happens on home assistant Android client.

**Comment by dermotduffy** [comment] 2023-02-13 15:19
@hardwareadictos What version of Android / how old is the hardware?

**Comment by felipecrs** [comment] 2023-02-13 15:25
> @dermotduffy I am not sure this is what you are looking for, is that the error message you were looking for from the console? <img alt="image" width="1168" src="https://user-images.githubusercontent.com/21988643/210246079-c5ade0d4-7651-41d6-9578-2fb9cb88213f.png">

This sounds like Frigate Hass Card before v4. I would recommend you try to uninstall the card entirely, making sure nothing is left about the Frigate Hass Card in your Dashboard Resources (Settintgs, Dashboards, Three dots, Resources). Then, install it again from HACS.

A reboot of HA may be necessary, but I would also recommend you clean all your browser caches. Also, if you are running on Android, clear the companion app cache in the Android settings.

**Comment by felipecrs** [comment] 2023-02-13 15:27
Ops, my bad. In fact the performance-related refactoring was not released in v4.

I would recommend you build the card by yourself from the release-4.1.0 branch. Here's how I do it from the VS Code Home Assistant add-on:

**Comment by hardwareadictos** [comment] 2023-02-14 08:12
> @hardwareadictos What version of Android / how old is the hardware?

Hey!

Pixel 7 with Android 13.
