### ISSUE TITLE
`No cameras support this view`

### ISSUE THREAD

**Issue by borgqueenx** [dermotduffy/frigate-hass-card#1533] opened 2024-09-15 03:14 UTC
Latest home assistant, the frigate card release of some hours ago, in home assistant companion app on latest samsung s21 firmware.
Quite randomly when opening a dashboard it reports "no cameras support this view". This was not the case before this latest beta.
I am using jspeg as live view, other then that settings are standard. Coming back to the dashboard or simply refreshing the page can make it work again.

![Screenshot_20240915_050703_Home Assistant](https://github.com/user-attachments/assets/58a09c77-b4d6-49da-8508-2c193533f529)

Didnt thought that frigare card could get better so huge thanks and compliments for this release!

**Comment by dermotduffy** [comment] 2024-09-15 03:20
> I am using jspeg as live view, other then that settings are standard. Coming back to the dashboard or simply refreshing the page can make it work again.

Is it possible you are using an older Frigate integration (i.e. not https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.4.0 ). I think this is what you might see in that case.

If I'm wrong, would you mind holding down the Frigate button for a few seconds and paste in the diagnostics here? Thanks!

**Comment by borgqueenx** [comment] 2024-09-15 10:43
i have the latest integration version. on my desktop, the icon for the menu does not show up, how do i get the logs then? i tried on my phone where the button shows up, but unfortunately the button to copy all the selected text does not appear. the whole text appears in the back of all other dashboard items which probably bugs the copy/paste menu on my samsung phone.

**Comment by EPiSKiNG** [comment] 2024-09-15 16:40
I am having the same issue.  If I hard refresh, or exit browser and re-open it usually fixes itself, but appears to be intermittent/random.  I can use the same browser on a different device and it works, then refreshing brings the error.  I am also using Frigate integration version 5.4.0.

For reference, I'm accessing cameras using go2rtc and MSE.  I also have HD and substreams in use.

**Comment by dermotduffy** [comment] 2024-09-15 23:21
> i have the latest integration version. on my desktop, the icon for the menu does not show up, how do i get the logs then? i tried on my phone where the button shows up, but unfortunately the button to copy all the selected text does not appear. the whole text appears in the back of all other dashboard items which probably bugs the copy/paste menu on my samsung phone.

For now, would you mind showing me the card config you used? Similarly @EPiSKiNG ?

Also useful would be a copy and paste of your Javascript console (F12 in Chrome/FF) to see if I can find anything useful in there....

**Comment by EPiSKiNG** [comment] 2024-09-16 00:54
Here's the JS error:

```
card-62302d66.js:75 
 cx: No cameras support this view
    at dx.getViewByParameters (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:10539)
    at dx.getViewDefault (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:9941)
    at dx.getViewDefaultWithNewQuery (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:11227)
    at ux._setViewGenericAsync (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:102:1521)
    at ux.setViewDefaultWithNewQuery (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:102:690)
    at Db.initializeMandatory (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:88:7087) 
Object
qp	@	card-62302d66.js:75
card-62302d66.js:75 
 cx: No cameras support this view
    at dx.getViewByParameters (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:10539)
    at dx.getViewDefault (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:9941)
    at dx.getViewDefaultWithNewQuery (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:93:11227)
    at ux._setViewGenericAsync (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:102:1521)
    at ux.setViewDefaultWithNewQuery (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:102:690)
    at Db.initializeMandatory (http://**myhomeassistant.url**/hacsfiles/frigate-hass-card/card-62302d66.js:88:7087) 
Object
qp	@	card-62302d66.js:75
```

and here's my card code:


```

type: custom:frigate-card
cameras:
  - camera_entity: camera.front_walkway
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.driveway
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.front_door
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.living_room_slider
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.bedroom_slider
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.side_yard
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
  - camera_entity: camera.pergola
    live_provider: go2rtc
    go2rtc:
      modes:
        - mse
    dependencies:
      all_cameras: true
    triggers:
      entities:
        - binary_sensor.0x3425b4fffe64e3f0_occupancy
view:
  triggers:
    actions:
      trigger: live
      untrigger: default
    filter_selected_camera: false
  default_reset:
    interaction_mode: all
  keyboard_shortcuts:
    ptz_left:
      key: ArrowLeft
    ptz_right:
      key: ArrowRight
    ptz_up:
      key: ArrowUp
    ptz_down:
      key: ArrowDown
    ptz_zoom_in:
      key: +
    ptz_zoom_out:
      key: '-'
    ptz_home:
      key: h
  default: live
menu:
  buttons:
    substreams:
      icon: mdi:high-definition
      priority: 100
    frigate:
      enabled: false
    cameras:
      enabled: false
    live:
      enabled: false
    clips:
      enabled: false
    snapshots:
      enabled: false
    recordings:
      enabled: false
    download:
      enabled: false
    camera_ui:
      enabled: false
    expand:
      enabled: false
    timeline:
      enabled: false
    media_player:
      enabled: false
live:
  transition_effect: none
  controls:
    thumbnails:
      mode: below
      show_favorite_control: false
      show_timeline_control: false
      show_download_control: false
  preload: true
  auto_play:
    - selected
    - visible
visibility:
  - condition: numeric_state
    entity: sensor.sun_solar_elevation
    above: -4
dimensions:
  aspect_ratio_mode: static
  aspect_ratio: '16:11'

```

**Comment by dermotduffy** [comment] 2024-09-16 03:03
@EPiSKiNG Are you using any query strings in the dashboard URL (like [this](https://card.camera/#/usage/url-actions)). Assume not.

**Comment by dermotduffy** [comment] 2024-09-16 03:14
@EPiSKiNG Please enable debug logging:

```yaml
debug:
  logging: true
```

When the card loads it should print out `'Frigate Card CameraManager initialized (...)`. I am curious to see if that shows up before or after the Javascript errors you included here. It's some sort of race condition ...

**Comment by dermotduffy** [comment] 2024-09-16 04:10
After struggling to get this to happen in Chrome, I can now somewhat reliably get it to happen in Firefox, investigation to continue tomorrow ...

**Comment by borgqueenx** [comment] 2024-09-16 05:28
I have it actively happening in chrome and on the home assistant companion app for android.

**Comment by EPiSKiNG** [comment] 2024-09-17 00:21
> @EPiSKiNG Are you using any query strings in the dashboard URL (like [this](https://card.camera/#/usage/url-actions)). Assume not.

Negative.  

Tried added the debug log, but I'm not savvy enough to find it :)  Looks like you've got a good test case working though.

Thanks again for your work on this!

**Comment by dermotduffy** [comment] 2024-09-17 01:11
> Tried added the debug log, but I'm not savvy enough to find it :) Looks like you've got a good test case working though.

Yes, think I figured out the issue, just need to find the right answer!

**Comment by voron69-bit** [comment] 2024-09-17 17:53
Happening here as well. Chrome/Brave/Firefox/HA App.

**Comment by dermotduffy** [comment] 2024-09-18 19:17
All my development effort is going into this bug. ETA: No later than this weekend.

**Comment by voron69-bit** [comment] 2024-09-18 19:33
For those in a panic,  you CAN just roll it back to the 5.0 version from the hacs page and be up in running in seconds.  Until this gets fixed.

**Comment by dermotduffy** [comment] 2024-09-19 04:49
If anyone suitably knowledgeable wants to try a PR to see if it fixes their issue, check out #1545 !

**Comment by conorlap** [comment] 2024-09-19 10:26
@dermotduffy PR #1545 seems to fix it for me! Thank you!

**Comment by dermotduffy** [comment] 2024-09-21 23:10
Please try the new release and see if it helps: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.2

**Comment by borgqueenx** [comment] 2024-09-22 03:03
This seems to have solved it! A bit early to say perhaps but looking good!

**Comment by freskog** [comment] 2024-09-23 20:37
6.0.0-beta2 fixes it if you don't use card actions in the url. For me it is still broken if I use the frigate action to select camera on load.

**Comment by dermotduffy** [comment] 2024-09-23 21:27
@freskog Can you provide an example URL that is still broken? Don't need the hostname, just the query string, so I can try to reproduce.

**Comment by dermotduffy** [comment] 2024-09-24 03:23
@freskog Nevermind, found a reproduction (half the battle). Stay tuned.

**Comment by dermotduffy** [comment] 2024-09-28 21:58
@freskog There's a new release, let me know if this works better for you: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v6.0.0-beta.4

**Comment by dermotduffy** [comment] 2024-10-04 14:56
I am going to assume this is now fixed. Thank you all for the help on this!

**Closed by dermotduffy** 2024-10-04 14:56 UTC
Labels: bug, waiting

**Comment by EPiSKiNG** [comment] 2024-10-04 15:13
Working well for me!  Thank you for all the support and effort in this project!!!
