### ISSUE TITLE
Improve card performance for low-end devices

### ISSUE THREAD

**Issue by Sarah-Connelli** [dermotduffy/frigate-hass-card#841] opened 2022-09-26 17:26 UTC
**Is your feature request related to a problem? Please describe.**
I often have a few of these on the page, and I've noticed that with all the great new features, it now is starting to perform suboptimally on some phones/tablets.

**Describe the solution you'd like**
Maybe an easy option in the integration setup itself where we can just click something to disable all the fancy timelining and pretty much everything else if at all possible, so that we go back to basics very efficient rapid displaying cards.

**Describe alternatives you've considered**
Rolling back to an older version.

**Additional context**
I think as a card it is starting to become more a central camera management interface, and this isn't what a card is supposed to be? (forgive me if I am wrong).

Maybe there can be a split, an actually feature-rich camera management interface for frigate integration with timelines/events and the works. But the cards just go back to basics, show a camera and its thumbnail events, optimized to the n-th degree to just a super fluid HA wall panel and smartphone user experience.

I guess the term 'bloated' comes to mind, Windows 11 is well known for it, 90% of the users won't need all the features, however they come preinstalled without giving us the option to have it or not. Sure can disable things or simply not use them via configuration, however they do still impact the speed and bandwidth that leads to a noticeable lag/delay.

**Comment by dermotduffy** [comment] 2022-09-27 02:37
Thanks for the comment @Sarah-Connelli .

* Having an entirely different version of the card would be a non-trivial overhead, I'd rather invest in improving the performance of the card as-is until I know for sure I can't push it any further.
* It could be argued there's already a low-resources version of this card: the stock HA glance card will show the stream with minimum overhead. Everything else is a feature continuum :-)

Can you comment on where you are seeing the slowdown? Is it during usage (what are you doing?), or initial load?

**Comment by Sarah-Connelli** [comment] 2022-09-27 10:58
Hi, this is one of those "I can't believe I'm asking for a less features version" cases.

* all those spinning loaders could be adding to the performance drop
* all the toasts could be adding to the performance drop
* all the extra lazy loading script executions could be contributing too

I guess everytime anything CSS animation and JS execution is used, there is a hit on mobile/tablet platforms, the PC eats it up without issue though.

This is your baby, and in your use-case it may be perfectly fine, however rest assured the latest version does run considerably slower on mobile platforms, the CPU hit on mobile platforms has increased phenomenally, and it hits you harder the more frigate-hass-cards you have on screen at the same time.

I guess we can agree that optimization is part and parcel of the ongoing efforts alongside enhancements/features.

**Comment by Sarah-Connelli** [comment] 2022-09-27 11:51
A suggestion?

How about a global configuration setting like how Microsoft tackled the whole 'visual fanciness' vs 'performance' Windows nightmare on devices with very basic gpu/cpu-core counts.

A global flag 'Performance, no effects' that is disabled by default, but which then means absolutely no CSS fades/slides/animations whatsoever for those who enable it? Then this could alleviate all performance issues on entry level tablets/smartphones?

**Comment by dermotduffy** [comment] 2022-09-27 13:54
> I guess we can agree that optimization is part and parcel of the ongoing efforts alongside enhancements/features.

Exactly, and an area I haven't really invested much. Shame on me, but also suggests there'll be at least some room for improvement here before more costly options.

> Edited to say, if one has the latest and greatest Samsungs/iPads and top-end smartphones, not an issue whatsoever... however here is the alarm-bell, I'm sure you'd agree, most will not be spending upwards of $£1k for a device to be stuck up on the wall just for HA.

100%.

> A global flag 'Performance, no effects' that is disabled by default, but which then means absolutely no CSS fades/slides/animations whatsoever for those who enable it?

I had the same thought. I could imagine that flag just setting other flags since at least some of the fanciness can already be disabled (it's just a pain to need to set many flags).

You missed a key question: in your experience is the issue at runtime (fanciness => problem) or load time (bundle size => problem)?

**Comment by Sarah-Connelli** [comment] 2022-09-27 14:06
Loading is very bad, that in the video example was actually the second time I went in, the first time was waiting for paint to dry.
In use, very very slow, to the point of simply not being useable whatsoever.

I also tried it on an iPad Pro 12.9" second gen, oh my goodness, just as slow, in many cases the spinning loaders just remained spinning.

**I will just for validation state "The frigate-hass-card card works absolutely beutifully on the PC (Ryzen) and my Snapdragon 845 powered smartphone" on the same local network. Also The Snapdragon 845 powered phone via 4G external network works great too.**

**Comment by dermotduffy** [comment] 2022-09-28 03:02
That video is painful to watch -- how old is that device roughly?

I think my main actions here are:

* Start using a low-end device for testing.
* Investigate shrinking the bundle size (somehow). 
* Make obvious performance tweaks (e.g. spinners for thumbnails are already gone)
* Add performance related configuration that can be enabled to set the card to a "minimum" mode to disable both expensive features, but also CSS fanciness.

**Comment by Sarah-Connelli** [comment] 2022-09-28 21:48
Sounds like a fantastic plan!!!

That particular device is from 2016, it is old, but not old enough to be discounted as it runs the HA android app nicely and handles SIP video-calling etc quite well.

However the older devices were not optimized for very busy 'modern CSS' activity, I have reason to believe not every modern function is backported with full 3D acceleration to older devices via the Android WebView on updates, and likewise for Apple's Safari (hence the constant complaints from people with older Apple devices, because Apple rather you buy a new device than admit the old device is perfectly capable if all they did was actually port bespoke optimisations back to older models in their IOS upgrades, shennanigans as per usual).

This card is indeed legendary, with a little extra re-factoring I think it can most definitely cover a range of devices from old to new, but yes agreed you would need an old device as a benchmark to work with. If anything, it is always fun trying to get the best out of older-tech, the best optimisations tend to be achieved that route.

Thank you for taking this issue seriously.

**Comment by dermotduffy** [comment] 2022-10-02 07:28
Another idea:

* Remove view history (currently not garbage collected).

**Comment by dermotduffy** [comment] 2022-10-10 03:11
@Sarah-Connelli I've made some progress on this (described in #861 and now merged into the `release-4.1.0` branch). If you're comfortable doing your own build (instructions on the README), give it a shot? I'd recommend you start with as empty a configuration as possible (ideally just the cameras), and then add:

```yaml
performance:
  profile: low
```

... into the configuration and see how it goes.

If you'd rather not do your own build, no worries, you can wait until the next release.

**Comment by felipecrs** [comment] 2022-10-10 05:09
@dermotduffy this is awesome. I'm trying to test here, and after switching to the new version, the card doesn't work for me anymore:


https://user-images.githubusercontent.com/29582865/194802163-8066fdfe-15e4-4606-b372-cec963a9747f.mp4

**Comment by dermotduffy** [comment] 2022-10-10 14:29
@felipecrs Hmm. Have not seen that. The definition that is the source of your error happens exactly once at the toplevel of the JS:

```sh
(~/src/frigate-hass-card/dist) $ egrep 'define.*action-handler-frigate-card' *.js
frigate-hass-card.js:customElements.define('action-handler-frigate-card', ActionHandler);
```

* Do you have the whole of the 'dist' directory from your build accessible in your HA instance? (i.e. not just `frigate-hass-card.js` like previously, now the whole `dist` directory content needs to be accessible from the same direction in which `frigate-has-card.js` lives).
* Is there any possibility you are sourcing both the old and the new versions in the same dashboard? (That would explain what you're seeing).

**Comment by felipecrs** [comment] 2022-10-10 14:31
> Do you have the whole of the 'dist' directory from your build accessible in your HA instance? (i.e. not just frigate-hass-card.js like previously, now the whole dist directory content needs to be accessible from the same direction in which frigate-has-card.js lives).

I guess so, everything is under `/config/www/custom/frigate-hass-card/`, which are a bunch of files. Do I need to add all of them to the lovelace resources, one by one in the UI?

**Comment by dermotduffy** [comment] 2022-10-10 14:40
> I guess so, everything is under /config/www/custom/frigate-hass-card/, which are a bunch of files. Do I need to add all of them to the lovelace resources, one by one in the UI?

No. As long as all the files are there, and `frigate-hass-card.js` is added as a lovelace resource (as it was before), it should "just work".

**Comment by felipecrs** [comment] 2022-10-10 14:40
https://user-images.githubusercontent.com/29582865/194891961-2c66c8f8-ac64-46af-b8a1-e277f99880ba.mp4

Unfortunately no luck yet.

**Comment by dermotduffy** [comment] 2022-10-10 14:45
Sadly I don't see anything obviously incorrect there (as long as `mode` is set to `dir` in your `build_frigate.card.sh`, which it must be as otherwise you wouldn't get all the chunks generated).

**Comment by felipecrs** [comment] 2022-10-10 14:46
Could it be the cache tag? `?cache=whatever`

I'll try without it.

**Comment by dermotduffy** [comment] 2022-10-10 14:46
Maybe try `Chrome devtools` -> `Network tab` -> filter on `frigate-hass-card` and see if `frigate-hass-card.js` is somehow being included twice.

**Comment by felipecrs** [comment] 2022-10-10 14:50
![image](https://user-images.githubusercontent.com/29582865/194893863-0fa1031a-a3b5-4875-96f7-3a546afd4374.png)

Interesting, I suppose there should be more files there. By the way the filter did not result in anything.

> Maybe try `Chrome devtools` -> `Network tab` -> filter on `frigate-hass-card` and see if `frigate-hass-card.js` is somehow being included twice.

![image](https://user-images.githubusercontent.com/29582865/194894183-cc108337-0a93-43be-a1c1-f31f2051867d.png)

I don't know how to read this :)

**Comment by felipecrs** [comment] 2022-10-10 14:52
Wow, ok, it worked in an anonymous tab. Then I cleaned the cookies and now it's working :)

Sorry about that.

**Comment by felipecrs** [comment] 2022-10-10 14:59
Wait, the issue has nothing to do with cookies. It, in fact, is because of the cache tag which I mentioned. After removing it, and ensuring a clean environment (like anonymous tab), it works. After adding the cache tag, it stops working even in a clean environment.

I think this may be a problem when it gets released, since HACS automatically adds such tag.

**Comment by felipecrs** [comment] 2022-10-10 15:55
Ok, if that's not weird enough, my HA running in Fully Kiosk is not working anymore:

![PXL_20221010_122926254](https://user-images.githubusercontent.com/29582865/194907007-26bd13e6-2fbe-4e67-8792-a8788fc79f8c.jpg)

I tried to clean up every possible thing, cookies, cache, but nothing works.

**Comment by felipecrs** [comment] 2022-10-10 16:32
Ok... updating/changing the WebView to Bromit using the Webview Manager magisk module seems to have fixed the issue.

**Comment by dermotduffy** [comment] 2022-10-10 19:04
> I think this may be a problem when it gets released, since HACS automatically adds such tag.

I have no idea why it wouldn't work without the tag. I'll try to add one ...

> Ok... updating/changing the WebView to Bromite using the Webview Manager magisk module seems to have fixed the issue.

Yeah. This is because I moved from `lodash` deepClone to structuredClone, which is higher performing. However, it's also less well supported and ironically the devices that need to (probably small) performance gain are also the devices most likely to have older versions of WebView.

I think I'll go back to lodash deepClone for now.

**Comment by felipecrs** [comment] 2022-10-10 19:11
> Yeah. This is because I moved from lodash deepClone to structuredClone, which is higher performing. However, it's also less well supported and ironically the devices that need the (probably small) performance gain are also the devices most likely to have older versions of WebView.

> 
> I think I'll go back to lodash deepClone for now.

Well, for me the issue is fixed. Feel free to collect feedback from others if you'd like as well.

**Comment by dermotduffy** [comment] 2022-10-10 19:19
> Well, for me the issue is fixed. Feel free to collect feedback from others if you'd like as well.

Suspect it'll keep tripping people up, and also suspect the gain is tiny, so not worth the support headache. It's a pity because it is [theoretically well supported](https://caniuse.com/?search=structuredclone) but you'll notice it only reached Android webview on the 27th September 2022 (and since some manufacturers are so lagging with updates, I don't think it can be relied upon just yet).

On the tagging, here's my network fetch list. Notice how the card is being sourced twice, once with the tag and once without it. This is the problem. I could hack it so it doesn't re-define the action handler if it's already defined, but it's still incurring a 2x download penalty that I'd like to try to resolve:

![Screenshot from 2022-10-10 12-15-44](https://user-images.githubusercontent.com/1136829/194937427-d7ddf9f4-2024-4399-9b2c-700de4725011.png)

**Comment by dermotduffy** [comment] 2022-10-11 02:11
@felipecrs Would you mind testing with #861 (now merged)?

**Comment by felipecrs** [comment] 2022-10-11 13:26
Awesome, it works now with the cache tag. :)

**Comment by skynet01** [comment] 2022-10-21 06:44
I love this card and use it for a few cameras that are not even connected to Frigate, I love the auto switch to a camera with movement feature. I agree with the original post about the performance. I have 10 of these cards in my dashboard and things slow down to a halt to the point that if I start interacting with a timeline on one of them it crashes HA. Maybe if the user disables the timeline button then the scripts shouldn't even load?

**Closed** 2022-10-21 14:57 UTC
Labels: performance
