### ISSUE TITLE
'Forbidden media source identifier' error after update

### ISSUE THREAD

**Issue by rjlee** [dermotduffy/frigate-hass-card#849] opened 2022-10-01 13:53 UTC
Using:

ha docker: 
frigate-hass-card: 4.0.0
frigate-hass-integration: 3.0.0
frigate: 0.11.0

I've previously had frigate 0.10 working in ha with the ha integration and this companion card.  I've now updated to frigate 0.11.0 and the above hass integration versions and now when configuring the companion card I see:

```
{
  "request": {
    "type": "media_source/browse_media",
    "media_content_id": "media-source://frigate/frigate/event-search/clips////lounge//",
    "id": 57
  },
  "response": {
    "code": "unknown_error",
    "message": "Forbidden media source identifier: frigate/event-search/clips////lounge//"
  }
}
```
The card configuration is:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.lounge_camera
```

Frigate media is browsable in the media player in home assistant and I've removed and reinstalled the hass-integration and the companion card in hacs.  I'm not sure why the card is having an issue accessing the media and if it's related to the companion card update or the frigate-hass-integration update, but figured I'd start here as the media is browsable in ha itself.

**Comment by dermotduffy** [comment] 2022-10-01 14:47
I believe this is a duplicate of https://github.com/dermotduffy/frigate-hass-card/issues/845 . I'll include you over there.

**Closed by dermotduffy** 2022-10-01 14:47 UTC
