### ISSUE TITLE
ReferenceError: TouchEvent is not defined

### ISSUE THREAD

**Issue by woempiej** [dermotduffy/frigate-hass-card#1183] opened 2023-05-23 18:56 UTC
Hi,

Since the latest update I am getting a major amount of errors in my logbook. 

![afbeelding](https://github.com/dermotduffy/frigate-hass-card/assets/62903344/6b10e0b4-4e59-47a1-bfff-5e31c1ce6721)

I think it is related to the default "zoomable = true" card parameter. Is this a new parameter?

This is one of my card diagnostics:
*****************************************************************************************************
{
  "ha_version": "2023.5.3",
  "card_version": "5.1.1",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0",
  "date": "2023-05-23T18:52:34.759Z",
  "frigate_version": {
    "326daf05f9b3da427b09bca83b91b0f0": "4.0.0/0.12.0-da3e197"
  },
  "lang": "en",
  "timezone": "Europe/Amsterdam",
  "git": {
    "build_version": "5.1.1-HEAD+g2d977be",
    "build_date": "Sat, 20 May 2023 20:35:29 GMT",
    "commit_date": "Sat, 20 May 2023 13:32:32 -0700"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.frigate_voordeur"
      },
      {
        "camera_entity": "camera.frigate_oprit"
      },
      {
        "camera_entity": "camera.frigate_tuin"
      }
    ],
    "view": {
      "default": "clip"
    },
    "menu": {
      "buttons": {
        "clips": {
          "enabled": true
        },
        "live": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        },
        "timeline": {
          "enabled": false
        },
        "download": {
          "enabled": false
        },
        "media_player": {
          "enabled": false
        }
      },
      "style": "outside"
    },
    "media_viewer": {
      "controls": {
        "thumbnails": {
          "mode": "none"
        },
        "title": {
          "mode": "none"
        },
        "timeline": {
          "mode": "below"
        }
      }
    },
    "media_gallery": {
      "controls": {
        "thumbnails": {
          "show_timeline_control": false,
          "show_favorite_control": false
        }
      }
    },
    "performance": {
      "profile": "high"
    },
    "live": {
      "controls": {
        "timeline": {
          "mode": "below"
        }
      }
    }
  }
}
*****************************************************************************************************

**Comment by dermotduffy** [comment] 2023-05-24 01:17
Duplicate of https://github.com/dermotduffy/frigate-hass-card/issues/1174 . Already fixed, will be in the next build

**Closed by dermotduffy** 2023-05-24 01:17 UTC
Labels: bug

**Comment by woempiej** [comment] 2023-06-16 20:00
Hi,

I am still seeing the error in my log after the update.
HA is updated to the latest version.

I am using firefox from a Windows PC.

![afbeelding](https://github.com/dermotduffy/frigate-hass-card/assets/62903344/abcee641-37b3-450d-b13e-a0cd03628046)

**Comment by woempiej** [comment] 2023-06-16 20:11
I manually deleted the cache and history of Firefox to be sure.
When opening a new session this is the result;

![afbeelding](https://github.com/dermotduffy/frigate-hass-card/assets/62903344/e5f33ea4-afff-4e41-bf49-2180560dd0c7)

**Comment by dermotduffy** [comment] 2023-06-17 00:33
@woempiej It is expected you will continue to see this message until there is a new card release (hopefully shortly).
