### ISSUE TITLE
frigate-card broken when card-condition refer to a card offline

### ISSUE THREAD

**Issue by itispip** [dermotduffy/frigate-hass-card#1384] opened 2024-02-28 12:35 UTC
**Issue:**
When there has no card-condition, one camera offline won't break the card, the offline card will either be displayed as black or as an image;  Below YAML have card-condition refer to a card id yard_camera_card, when this camera got offline, the whole frigate_card won't work including the online living_room_camera

YAML Code
========

type: custom:frigate-card
cameras:
  -- camera_entity: camera.backyard_1
    id: yard_camera_card
    live_provider: go2rtc
  -- camera_entity: camera.camera_1
    id: livingroom_camera_card
    live_provider: go2rtc
elements:
  **-- type: custom:frigate-card-conditional
    conditions:
      camera:
        -- yard_camera_card**
view: {}

**What's expected**
one camera offline won't break the whole card, the offline card will either be displayed as black or as an image;

**Comment by msth** [comment] 2024-03-01 06:04
have the same problem. Unfortunately for me the vacuum cleaner exists as a camera element. but this does not send an image in the proper sense and is therefore offline. Now no cameras are displayed

**Comment by REASystemeEDV** [comment] 2024-03-20 07:54
![image](https://github.com/dermotduffy/frigate-hass-card/assets/162441200/7e52d4b1-04db-401c-a10f-aebada496e6f)

**Comment by msth** [comment] 2024-03-20 07:55
![image](https://github.com/dermotduffy/frigate-hass-card/assets/1927680/b7e8631e-4bf3-4b26-b86f-88d7593833fe)

**Comment by REASystemeEDV** [comment] 2024-04-11 08:48
the problem is still there

**Comment by Gadeo** [comment] 2024-04-22 06:20
Yes, still the problem. I got  five cameras and one is online only at night. So sadly I  eliminated frigate-card for work properly. Any suggestion?

**Comment by dermotduffy** [comment] 2024-04-23 02:31
FYI: This is already fixed in the `dev` branch, so it's just a matter of waiting for the next release. The `dev` branch will render an error for a broken camera, but the rest of the card should otherwise work just fine.

**Comment by dermotduffy** [comment] 2024-09-28 22:27
[Issue cleanup] I believe this is fixed with the `v6` releases, please re-open if not.

**Closed by dermotduffy** 2024-09-28 22:27 UTC
Labels: bug
