### ISSUE TITLE
Query string from lovelace navigation action only works the first time

### ISSUE THREAD

**Issue by vangorra** [dermotduffy/frigate-hass-card#1186] opened 2023-05-27 14:28 UTC
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**
N/A

**Browser and Operating System:**
Firefox 113.0.2 (64-bit)
Ubuntu 23.04

**Description of problem:**

My configuration:
- View (in panel mode) with single frigate card. (path /lovelace/camera_chickens)
  - Frigate card is configured with 2 cameras. Camera ids: henhouse, chicken_coop
- Dashboard has buttons with tap_action that navigates to:
  - navigation_path: /lovelace/camera_chickens?frigate-card-action:camera_select=henhouse 
  - navigation_path: /lovelace/camera_chickens?frigate-card-action:camera_select=chicken_coop 

What works:
- Enter URL directly in browser.
- Refreshing dashboard, clicking either button the first time.

What doesn't work:
- From dashboard, click henhouse button.
  - This takes you to the henhouse camera.
- Go back to the dashboard (using the side nav, or browser back buttons).
- Click on the chicken_coop button.
  - This takes you to the henhouse (the last camera visible). 

**Frigate card diagnostic information**

```json

```

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

**Comment by dermotduffy** [comment] 2023-05-27 21:12
Initial response: Right now, the query string is intentionally only parsed on initial card render as you say. In this case, HA is probably disconnecting the already rendered card from the DOM and then reconnecting it as you change dashboards, which means the query string has no effect when the old DOM is reconnected.

So this is not a bug per se (in that it's intentionally implemented like that), but let me see if I can have the card re-parse the query string if the DOM is reconnected.

**Comment by rodgon81** [comment] 2023-06-09 16:28
> Initial response: Right now, the query string is intentionally only parsed on initial card render as you say. In this case, HA is probably disconnecting the already rendered card from the DOM and then reconnecting it as you change dashboards, which means the query string has no effect when the old DOM is reconnected.
> 
> So this is not a bug per se (in that it's intentionally implemented like that), but let me see if I can have the card re-parse the query string if the DOM is reconnected.

Hello, I have exactly the same problem as indicated by vangorra.

From what I saw in the code, the function that parse the url is "firstUpdated()" in "card-67eaecc9.js", and it is only called when I reload the page:

You indicate that the behavior is intentional in this way. So I have the question:

How could we use the action in the URL more than once without completely reloading the page, so that we have a dashboard with tap_action navigating to a specific camera on a multi-camera frigate-card?

Thank you

**Comment by dermotduffy** [comment] 2023-06-10 18:37
@rodgon81 

> How could we use the action in the URL more than once without completely reloading the page, so that we have a dashboard with tap_action navigating to a specific camera on a multi-camera frigate-card?

I can't tell what you mean by "dashboard" in the above. If you mean having an icon on the card itself, that navigates to a particular camera in that card, you can do:

```yaml
elements:
  - type: custom:frigate-card-menu-icon
    icon: mdi:chair-rolling
    title: Office
    tap_action:
      action: custom:frigate-card-action
      frigate_card_action: camera_select
      camera: camera.office
```

... if you mean having an action somewhere _else_ on your Lovelace dashboard (as in the original issue text), and you want it to tell a Frigate card also on that same dashboard to go to a particular camera, then I agree there is no good way to do that today. Even the fix I described (`have the card re-parse the query string if the DOM is reconnected`) probably would not work for you, since there is no DOM disconnect/reconnection happening for you.

I'll have to think more on how best to do this.

**Comment by rodgon81** [comment] 2023-06-10 21:11
Thank you @dermotduffy.

yes, this explanation indicates what I need (my English is not the best):
> ... if you mean having an action somewhere else on your Lovelace dashboard (as in the original issue text), and you want it to > tell a Frigate card also on that same dashboard to go to a particular camera

Ok, if you give a solution to this, I would appreciate it if you would inform me in this same post.

Thank you.

**Comment by dermotduffy** [comment] 2023-06-11 22:26
https://github.com/dermotduffy/frigate-hass-card/pull/1198 will be in the next build which should fix this for you. It'll be in the next build!

**Closed by dermotduffy** 2023-06-11 22:26 UTC
Labels: bug
