### ISSUE TITLE
Thumnails not scrollable

### ISSUE THREAD

**Issue by thundergreen** [dermotduffy/frigate-hass-card#185] opened 2021-11-07 17:32 UTC
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
latest 2.0.0
**Last working release (if known):**
xxxx
**Browser and Operating System:**
Microsoft Edge / Chrome / Firefox

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment] 2021-11-07 20:03
I cannot reproduce this in Chrome, Firefox or Safari. Here's what I see (not a great example as there's only a few thumbnails, but you get the idea of the way it scrolls): 

![gallery-scroll](https://user-images.githubusercontent.com/1136829/140660044-93af9ec0-ddf2-4f67-9b34-dc965d9017c9.gif)

**Comment by thundergreen** [comment] 2021-11-07 21:18
Only reason I can think of is that I out this cards in swipe card. Maybe then it won't work I'll check this and report if scroll works outside swipe card

**Comment by thundergreen** [comment] 2021-11-07 21:36
Just tested ..works only with mouse wheel to school thumbnails. Not with touchscreen :(

**Comment by dermotduffy** [comment] 2021-11-07 22:09
Touchscreen works fine for me. Did you try it without the swipe card?

**Comment by dermotduffy** [comment] 2021-11-08 15:34
Figured. Think you're out of luck then. Maybe the swipe card folks have some ideas?

**Comment by dermotduffy** [comment] 2021-11-10 03:35
I'm going to close this as I don't think there's anything that can be done on the card side. If you learn otherwise (e.g. there's something the card could do to make touch scrolling work for your instance), please don't hesitate to re-open and we'll discuss. Thanks!

**Closed by dermotduffy** 2021-11-10 03:35 UTC
Labels: question
