### ISSUE TITLE
JSMPEG view generates a lot of "login attempt failed" errors in HA

### ISSUE THREAD

**Issue by alexdelprete** [dermotduffy/frigate-hass-card#109] opened 2021-10-09 01:29 UTC
It only happens with `frigate-jsmpeg`. If I switch to webrtc I don't see these.

```
2021-10-09 02:43:59 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from G37.axel.dom (10.1.10.41). (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4644.0 Safari/537.36 Edg/96.0.1032.0)
2021-10-09 02:44:05 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from G37.axel.dom (10.1.10.41). (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4644.0 Safari/537.36 Edg/96.0.1032.0)
2021-10-09 02:44:11 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from G37.axel.dom (10.1.10.41). (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4644.0 Safari/537.36 Edg/96.0.1032.0)
2021-10-09 02:44:17 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from G37.axel.dom (10.1.10.41). (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4644.0 Safari/537.36 Edg/96.0.1032.0)
2021-10-09 02:44:24 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from G37.axel.dom (10.1.10.41). (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4644.0 Safari/537.36 Edg/96.0.1032.0)
2021-10-09 02:44:31 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from G37.axel.dom (10.1.10.41). (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4644.0 Safari/537.36 Edg/96.0.1032.0)
2021-10-09 02:44:39 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from G37.axel.dom (10.1.10.41). (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4644.0 Safari/537.36 Edg/96.0.1032.0)
2021-10-09 02:44:46 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from G37.axel.dom (10.1.10.41). (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4644.0 Safari/537.36 Edg/96.0.1032.0)
```

**Comment by alexdelprete** [comment] 2021-10-09 03:46
> This is already fixed, but not yet released. See the workaround here

I'm the one who found the workaround in #92. :)

But it doesn't solve the login error, otherwise I would not have them since I'm using the workaround since the beginning.

**Comment by alexdelprete** [comment] 2021-10-09 10:43
No problem, that's why I added the smile. I know it gets confusing. :)

Nope, I have 1 card and 1 camera (a doorbell). JSMPEG works fine, but many authentication errors, like other users reported in the other issue, can't remember the #, where you suggested to put the optional camera name to fix JSMPEG. They see those login errors too.

I think that JSMPEG opens several unauthenticated sessions to HA in the init phase...hence those errors...but I'm just speculating...

**Comment by dermotduffy** [comment] 2021-10-09 15:18
OK, so it appears to work fine, but you end up with log lines. Hmm.

I don't think that theory is correct, as there's only one URL passed to JSMPEG and it's an authenticated/signed one. JSMPEG doesn't know anything about HA, it's the card that is linking JSMPEG+HA (and doing so only with one single URL).

If it's not just a rogue card you have running somewhere else (without `frigate_camera_name`) the only other thing I can think of is somehow the camera name is getting messed up and so the Frigate integration is rejecting the URL for some reason.

Since you're comfortable with the JS debugger (as I recall from the other bug), I wonder if you could attach a breakpoint here:

https://github.com/dermotduffy/frigate-hass-card/blob/main/src/components/live.ts#L223

... and then see what the value of `jsmpeg_url` is? (By just typing `jsmpeg_url` into the console after the breakpoint is reached).

**Comment by alexdelprete** [comment] 2021-10-09 22:59
Sorry Dermot but I'm not really a JS expert, I'm a good tinkerer, and I'm using MS Edge internal debugger.

Couldn't find the live.ts code anywhere, but I played a little bit with the debugger, and this is what I came up with:

I started the debugger/console while in edit mode of the frigate-hass-card, so I had the options open and the preview, it was working, but when I went to console I found these errors:

![image](https://user-images.githubusercontent.com/7027842/136675651-570646d0-bbb8-4a28-9b0f-a48072cc36ca.png)

I noticed the url contained a double frigate/frigate path, I don't know if that's correct. So I went in the source code of frigate-hass-card.js (it's the only source I see in the debugger) and put a breakpoint here:

![image](https://user-images.githubusercontent.com/7027842/136675691-ef126319-be32-4783-b305-0a7576c6ad3b.png)

I also put this.url in Watch section of the debugger. When it stopped on the breakpoint, the content of the url was:

```
ws://hass.axel.dom:8123/api/frigate/frigate/jsmpeg/citofono?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIyNjJhZTU1MmNkMzU0MjJjOTE1ZDdiZjNlMDBkZjk3ZSIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9qc21wZWcvY2l0b2Zvbm8iLCJpYXQiOjE2MzM4MTg2NzksImV4cCI6MTYzMzgxODcwOX0.E6uYTU2PmyZ8r2f48XlZbJEMVJFM_DQiOxLb2lnRDls"
```

The only thing strange I notice is the double path frigate/frigate": /api/**frigate/frigate**/jsmpeg/

I hope that's the url you were looking for, and sorry if I'm not that good with JS stuff.

**Comment by dermotduffy** [comment] 2021-10-17 23:34
@alexdelprete Just checking in Alessandro, are you still seeing these errors in your log recently?

I continue to have no examples on my end:

```sh
$ grep "Login attempt or request" /etc/home-assistant/home-assistant.log
$
```

**Comment by dermotduffy** [comment] 2021-10-18 00:35
Do you get these messages immediately upon loading, or it takes some time for them to appear? If the latter, any idea how long?

[I'm wonder if it's some auth expiration issue and/or if I'm not waiting long enough with the JSMPEG live view loaded]

**Comment by alexdelprete** [comment] 2021-10-18 01:05
Immediately on loading...before the stream is shown...

I just restarted HA to update some components, and when I went to the card...it didn't happen...no warnings.

Also, the fact that after refresh of the page it doesn't happen anymore, has to mean something...unfortunately I'm not able to consistently reproduce it. It's not the browser, because it also happened when I used the HA mobile client.

**Comment by dermotduffy** [comment] 2021-10-18 04:19
Experimental fix will be in the next build to extend the expiration of the signed JSMPEG URL. I think this is a long-shot, but as I still cannot reproduce this myself "naturally" it's worth a shot to see if it helps. This would fix the issue if too long of a time elapsed between signing the URL, and JSMPEG player using it -- the merged PR expands that expiry time. If I **reduce** the expiry time, I can reproduce the error messages included in this bug myself, so perhaps some delay is causing you to hit that expiry time sooner?

Lets see where we stand after the next build ...

**Comment by dermotduffy** [comment] 2021-10-18 19:50
Thanks for trying it -- it was a long-shot anyway. OK, lets continue to leave this bug open and see if others have the same issue and/or if anyone figures out a pattern of when/how it happens.

**Comment by alexdelprete** [comment] 2021-10-18 19:59
If I find something I'll let you know...thanks for your support.

**Comment by oramirite** [comment] 2021-10-20 17:29
Just wanted to chime in that I'm getting this issue as well. It kicked off at a strange time too - I had upgraded this card much earlier in the day, but it wasn't until I started reloading my automations.yml file that I started to get this. I've basically been flooded with these messages ever since.

**Comment by Mincka** [comment] 2021-10-21 05:49
I have a tablet with a few cards in live view with JSMPEG. If I restart the addon, the cards becomes black and at this time I start getting authentication errors. As soon as I refresh the browser, the cards reload, with the live view in JSMPEG and the authentication errors stop. So in my opinion, it happens when the connection breaks (for any reason). The card is unable to get it and reset its session automatically.

**Comment by blakeblackshear** [comment] 2021-10-22 00:46
I am initializing JSMpeg in the web UI [with audio disabled](https://github.com/blakeblackshear/frigate/blob/master/web/src/components/JSMpegPlayer.jsx#L11-L16). I don't think it has anything to do with this issue, but it should prevent that console message.

**Comment by Mincka** [comment] 2021-10-30 05:10
Finally, after a few hours, it continues but I don't manage to fix it with ctrl+F5 in my case.
`Login attempt or request with invalid authentication from localhost (127.0.0.1). See the log for details.`
Do you also have errors from `localhost` sometimes @alexdelprete ?

**Comment by dermotduffy** [comment] 2021-10-30 05:26
I would recommend you don't bother testing this right now, and wait for the next build as I am hopeful it will resolve it. I'll ping this thread when the build is ready, probably within the next week.

**Comment by alexdelprete** [comment] 2021-10-30 18:55
> Do you also have errors from `localhost` sometimes @alexdelprete ?

Never from localhost, always from the IP of my notebook or the IP of my mobile phone, from where I access HA.

Maybe you use a proxy to access HA?

**Comment by alexdelprete** [comment] 2021-10-30 18:56
> I would recommend you don't bother testing this right now, and wait for the next build as I am hopeful it will resolve it. I'll ping this thread when the build is ready, probably within the next week.

So you were able to reproduce it? Great news.

**Comment by dermotduffy** [comment] 2021-11-07 16:41
There's a v2.0.0 pre-release that maybe will fix this issue:https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-1602062

Anyone who is still seeing these log entries with a JSMPEG live view, check it out ;-)

**Comment by alexdelprete** [comment] 2021-11-07 17:32
I was waiting for it...:)

Installed it a couple of hours ago...will let you know...thanks a lot.

**Comment by alexdelprete** [comment] 2021-11-10 03:06
Dermot, I can confirm the problem is fixed, I only had 1 event since I installed it, and it was a couple of hours after the upgrade to this latest pre-release version. :)

Everything's working smoothly, great job, thank you so much for the support, I appreciate it.

Alessandro

**Comment by felipecrs** [comment] 2022-02-14 21:13
I started to get these all the time again, but I believe it's since the card was updated to v3.0.0-rc.1.

**Comment by felipecrs** [comment] 2022-02-18 14:43
@dermotduffy if I'm the only one with this issue, please do not delay the v3.0.0 release because of it.

**Comment by dermotduffy** [comment] 2022-03-04 03:18
@felipecrs Is this still happening for you with v3.0.0-rc.1?

**Comment by felipecrs** [comment] 2022-03-04 03:26
Yes, still happening with v3.0.0-rc.1. But I have no clue on what makes my environment special to trigger this issue. I just know that if I restart HA, I start to receive a lot of these errors for the next several minutes. After some minutes (maybe hours?) online, I stop receiving them.

So, I have an environment where I can reproduce, but I don't know how you can reproduce it... in case it helps, and you are willing to, we can have a call (Discord (felipecrs#8767) or anywhere else).

**Comment by dermotduffy** [comment] 2022-03-04 03:29
Sent you a discord invite!

But let me play around with it a little. Knowing it happens to you on restart gives me something to start with.

**Comment by oramirite** [comment] 2022-03-04 03:34
I'm sorry for the unhelpful comment... but this whole thing is ridiculous.
This whole issue is dancing around Home Assistant's absolute trash logging.
If it gave us a little bit more information this issue would have been
solved last year.

Sorry but I consider it absolutely insane that a little tiny bug in a
plugin causes a false positive security error. If I seem fustrated it's
because I am.... HA doesn't give 2 craps about security, and the fact that
this error can be triggered by the technical equivalent of a speck of dust
floating by is evidence of that.

Just to be clear: at this point it's become clear to me that this error is
no fault of the plugin author. This same error gets caused by other plugins
and the log messages are similarly useless.

I don't know how we're going to solve this problem without escalating the
root cause of not having enough logging information to identify the issue.
Nabu Casa needs to take a look at this point and give us better tools to
find the issue.

**Comment by dermotduffy** [comment] 2022-03-04 05:19
> Just to be clear: at this point it's become clear to me that this error is
> no fault of the plugin author. 

@oramirite I understand the frustration, and agree it is difficult to debug these errors. I also agree these are small issues and that it is unfortunate HA labels them as serious issues when they are not. However, these issues **_are_** an error with the cards. From HA's perspective, it's receiving an invalid/unauthorized request. I could imagine improvements in logging (e.g. only log it if it repeatedly happens, or -- perhaps a much better option -- allow security tokens to persist through restarts or allow some other mechanism of communication between cards and HA). If you're a paying Nabu Casa customer, this could be an issue to try to draw their attention to, if you're not in a position to contribute improvements yourself.

Anyway, I hope I've improved this for this card with the attached PR. @felipecrs I could reliably reproduce this on HA restart (in particular with the HA Android app), and after this fix I _cannot_ reproduce it -- so maybe ...

**Comment by alexdelprete** [comment] 2022-03-04 11:06
Dermot, for what it's worth, I'm not seeing these errors. If you need me to test anything please let me know.

**Comment by felipecrs** [comment] 2022-03-04 11:06
Wow, I just tested here. No more errors from what it seems!

**Closed** 2022-03-04 15:49 UTC
Labels: bug
