### ISSUE TITLE
Bug: Download button not working on Android companion app

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#241] opened 2021-12-14 13:52 UTC
**Checklist:**

- [ yes ] I updated to the latest version available
- [ yes ] I cleared the cache of my browser

**Release with the issue:**
HA: 2021.12.1
frigate-hass-card: v2.1.0 
AlexxIT/WebRTC card: v2.2.0

**Last working release (if known):**
Not known

**Browser and Operating System:**
Android companion app - beta-1776-8c5149dd-full (issue is also happening on latest Play Store version)

**Description of problem:**

Download button not working on Android companion app. No action occurs when this button is tapped. Works fine on browser. 

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

N/A

**Comment by dermotduffy** [comment] 2021-12-14 15:35
Thanks for the report @conorlap !

Confirmed on my end. I think the user agent check added in https://github.com/dermotduffy/frigate-hass-card/pull/219 isn't working correctly. I'll take a look.

**Comment by Driminary** [comment] 2022-01-11 00:57
Also had this problem so did some digging this evening. It looks like the UserAgent strings for the companion apps start with different values: 

- Android: **"HomeAssistant/"** _([L108_ here](https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L108))_
- iOS: **"Home Assistant/"** _([L58 here](https://github.com/home-assistant/iOS/blob/master/Sources/Shared/API/HAAPI.swift#L58))_

Modifying code.ts [L621](https://github.com/dermotduffy/frigate-hass-card/blob/main/src/card.ts#L621) from:
`    if (navigator.userAgent.startsWith("Home Assistant/")) {`

To: 
`    if (navigator.userAgent.startsWith("Home Assistant/") || navigator.userAgent.startsWith("HomeAssistant/")) {`

Fixed the issue for me. (Though because I'm on a Chromebook I had to retrospectively make this change in the released .js file instead of building the code from source...)

Here's my modified version @conorlap if you want to see if it works for you? - [frigate-hass-card.zip](https://github.com/dermotduffy/frigate-hass-card/files/7842807/frigate-hass-card.zip)

@dermotduffy - I'll leave it with you to decide how best to fix this permanently, but hopefully this helps. :)

**Comment by dermotduffy** [comment] 2022-01-17 23:16
Thanks to @NickM-27 I believe this is now fixed (and verified working on my Android device) and should be available in the next release.

**Closed by dermotduffy** 2022-01-17 23:16 UTC
Labels: bug

**Comment by mathieuruellan** [comment] 2024-06-10 06:16
Hello, I don't know if it's a regression or due to this component.
At the moment, I can download clips/snapshots from my laptop, with the arrow button in the card . But download fails from my phone (android 14)
I've updated this morning, everything is up to date (frigate/stable, homeassistant/latest frigate 5.2.0,  frigate card 5.2.0), .

**Comment by dermotduffy** [comment] 2024-06-11 02:05
Known issue with the iOS HA app: https://github.com/home-assistant/iOS/issues/2283
