### ISSUE TITLE
Live Carousel loads halfway away from the center

### ISSUE THREAD

**Issue by satyambaba** [dermotduffy/frigate-hass-card#651] opened 2022-06-09 09:19 UTC
**Checklist:**

- [Yes] I updated to the latest version available
- [Yes] I cleared the cache of my browser

**Release with the issue:**
V3.0.0
**Last working release (if known):**

**Browser and Operating System:**
It is happening on both, chrome browser and HA android app.
Google Chrome Version 102.0.5005.63 (Official Build) (64-bit)
HA Android App version - 2022.3.0 on Pixel 3 XL (Android 12)
HA System - HA Blue (HA Core 2022.6.2, Supervisor 2022.05.3, OS 8.1).

**Description of problem:**
Live Carousel loads halfway away from the center like 90% of the time. Refresh also doesn't work. If I click on clips gallery and then back to Live view, it sorts out this issue, however it appears again next time it gets refreshed. Already tried removing and reinstalling this card from HACS, but to no avail. Please see the images below.

Google Chrome screenshot -
![Screenshot 2022-06-09 134737](https://user-images.githubusercontent.com/6833101/172811194-ecab5aa0-cdb4-4ced-a547-f12390ba915b.jpg)

Android App scrennshot -
![Screenshot_20220609-144553](https://user-images.githubusercontent.com/6833101/172812481-ca26569a-e019-41ea-81fc-73308c9db2df.jpg)

**Javascript errors shown in the web inspector (if applicable):**

No Javascript error noticed in the Chrome JS console.

**Additional information:**

**Comment by dermotduffy** [comment] 2022-06-09 13:23
I saw this most prominently in Safari, but I think others have seen it in chrome. I also believe it's fixed in v4.0.0 which is not yet released (but will be imminently). If you are adventurous you could try building your own from the build instructions in the README and the release-4. 0.0 branch, otherwise wait a little bit and try again with the next release?

**Comment by satyambaba** [comment] 2022-06-09 17:50
> I saw this most prominently in Safari, but I think others have seen it in chrome. I also believe it's fixed in v4.0.0 which is not yet released (but will be imminently). If you are adventurous you could try building your own from the build instructions in the README and the release-4. 0.0 branch, otherwise wait a little bit and try again with the next release?

Thanks for this info! I'll try the v4.0.0 and check. If it doesn't work, I can patiently wait for the next release. Thanks again for your efforts.

**Comment by dermotduffy** [comment] 2022-06-10 03:05
OK! I'll close this for now, but please definitely re-open if you find this in v4 (whether you build yourself, or not).

**Comment by nathanmarlor** [comment] 2022-06-11 19:52
Also experiencing this. Only difference from OP is I'm using Dwains Dashboard.

Seeing the same behaviour on the latest release-4.0 branch. Navigating away from live and back resolves the issue. 

![Screenshot 2022-06-11 at 20 48 35](https://user-images.githubusercontent.com/3436911/173202768-5cf07e40-d34a-445d-93c3-f796e9cfa890.png)

![Screenshot 2022-06-11 at 20 51 18](https://user-images.githubusercontent.com/3436911/173202827-6e4ce417-a679-4f7c-b532-63fe21dba8c8.png)

`embla__container` seems to be set to 50%, reverting to 0% after refresh.

Happy to provide any more info...! :)

**Comment by dermotduffy** [comment] 2022-06-11 19:54
Thanks @nathanmarlor ! When did you do your v4 build? Do you have any reproduce steps I should be using?

**Comment by nathanmarlor** [comment] 2022-06-11 19:56
@dermotduffy 5 minutes ago :)

I can send you a screen record privately if that helps?

**Comment by dermotduffy** [comment] 2022-06-11 19:59
@nathanmarlor Heh, great. Yes, that would really help! Sadly I cannot reproduce this, but having seen it before in the Safari case it's probably some resize or load related race-condition, which means guesswork on my behalf may be necessary ... seeing a screenshot/video would help me guess in the right direction!

**Comment by nathanmarlor** [comment] 2022-06-11 20:05
In your inbox :) Let me know if you need any more info.

**Comment by dermotduffy** [comment] 2022-06-11 20:20
@nathanmarlor Got it, thanks! PS: If you have multiple cameras, can you drag the carousel when it's in this "half" state or is it stuck?

**Comment by nathanmarlor** [comment] 2022-06-11 20:26
@dermotduffy in your inbox 👍

**Comment by dermotduffy** [comment] 2022-06-12 03:06
@nathanmarlor If you can, would you mind doing a build with https://github.com/dermotduffy/frigate-hass-card/pull/676 applied? I still cannot reproduce this myself, but this may help.

**Comment by nathanmarlor** [comment] 2022-06-12 07:22
@dermotduffy same behaviour unfortunately. Haven't had long enough to fully confirm but also feels like there's a performance hit on this build - 1-2 second pause after the initial load.

**Comment by dermotduffy** [comment] 2022-06-12 15:33
@nathanmarlor Dang. Thanks for trying. Very hard to debug without being able to reproduce. I was using my prior identified Safari issue as a proxy. If you had such an environment, that would be amazing.

One thing: Can you hold down the Frigate icon menu button for a few seconds, and paste the diagnostics that show up? I can try to more exactly replicate on my side too...

**Comment by nathanmarlor** [comment] 2022-06-12 15:40
@dermotduffy Thanks - should be able to get an environment stood up tomorrow, will ping you some creds as soon as it's ready. Appreciate your efforts!

Here's the extra debug:

```
{
  "ha_version": "2022.6.2",
  "card_version": "4.0.0-rc.1",
  "frigate_version": {
    "cdc1dd1c3dbc018940360df213edc6c3": "2.3/0.11.0-ba119e4"
  },
  "lang": "en",
  "config": {
    "input_name": "",
    "input_entity": "camera.front",
    "cameras": [
      {
        "camera_entity": "camera.front"
      }
    ],
    "dimensions": {
      "aspect_ratio_mode": "dynamic"
    },
    "live": {
      "auto_unmute": "never",
      "draggable": true,
      "lazy_load": false
    },
    "media_viewer": {
      "auto_unmute": "all"
    },
    "menu": {
      "buttons": {
        "download": {
          "enabled": false
        },
        "frigate_ui": {
          "enabled": false
        },
        "snapshots": {
          "enabled": false
        }
      }
    },
    "type": "custom:frigate-card",
    "view": {
      "camera_select": "live",
      "default": "live",
      "update_force": false
    }
  }
}
```

**Comment by nathanmarlor** [comment] 2022-06-13 09:15
@dermotduffy - environment ready for you, credentials in your inbox 👍

**Comment by felipecrs** [comment] 2022-06-13 17:11
@dermotduffy this seems pretty much as the ocasional issue which I showed to on Discord, although for me, I see it more frequently in the _live_ view.

**Comment by felipecrs** [comment] 2022-06-13 17:22
https://user-images.githubusercontent.com/29582865/173409314-bd3e5caa-a6b4-403f-9986-f997ce447941.mp4

As you have asked: no, scrolling the camera does not work when this issue is active.

**Comment by dermotduffy** [comment] 2022-06-13 19:13
Thanks @felipecrs . Sadly that doesn't make it happen for me, but @nathanmarlor has given me access to a dev environment in which it _is_ broken, so at least I have something to play with and test fixes against.

Current theory: The carousel is measuring the slide sizes when the elements are not displayed (Nathan is using Dwain's dashboard which is hiding elements between clicks, so the slides has 0 size), and then when they _are_ displayed the slides sizes are not being re-calculated causing the carousel to jam.

**Comment by dermotduffy** [comment] 2022-06-14 04:34
@nathanmarlor Would you mind re-testing the now updated #676 ? This worked for at least @felipecrs 's problem.

**Comment by nathanmarlor** [comment] 2022-06-14 07:13
Fixed!! Thanks @dermotduffy for your efforts!!

**Comment by dermotduffy** [comment] 2022-06-14 13:20
Fix merged. This was a weird one. Thank you @nathanmarlor and @felipecrs for the test environments, but have been a huge amount of guesswork otherwise.

**Closed by dermotduffy** 2022-06-14 13:20 UTC
Labels: bug
