### ISSUE TITLE
Failed to receive response from Home Assistant for request.

### ISSUE THREAD

**Issue by HHUBSS** [dermotduffy/frigate-hass-card#911] opened 2022-12-31 05:46 UTC
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Last working release (if known):**
0.10.1-83481AF

**Browser and Operating System:**
Mobile App iOS and Android, Web Google Chrome

**Description of problem:**
So I'm running frigate and home assistant in docker. I also use the frigate card to show the camera in lovelace. After the camera feed was loaded, it shows like this

![image](https://user-images.githubusercontent.com/89816305/210126509-a88a22c7-1f5b-42a0-9ff9-882655eed624.png)

It's been awhile since I get this error and I want to fix this once and for all. Can you help me please?

**Comment by dermotduffy** [comment] 2022-12-31 16:48
This is likely caused by an exception being thrown in by the Frigate integration (and the card is just passing that on to you). Take a look in your Home Assistant logs when that happens, and you'll see an exception -- paste it here and lets take a look!

**Comment by HHUBSS** [comment] 2023-01-01 13:25
It happened today 9:20 PM and I don't see an exception error. I only see this log which is related to frigate. I don't know what it means either.

![error](https://user-images.githubusercontent.com/89816305/210172136-d7e37ab4-8a9b-4a15-ac9a-1682f617667a.jpg)

**Comment by dermotduffy** [comment] 2023-01-01 18:32
Home Assistant is having difficulties talking to your Frigate backend, and the card is just showing you that. I'd check your Frigate logs and see if you can find any matching errors.

Do you have very large numbers of events? If so, it could be related to: https://github.com/dermotduffy/frigate-hass-card/issues/897

**Comment by HHUBSS** [comment] 2023-01-02 01:59
I have 60 days of retention. Is this "very large"? Should I make this 30 days or even lower?  Or is it possible to retain 60 days in the frigate server and just show 10 days on the frigate card for the home assistant?

**Comment by dermotduffy** [comment] 2023-01-02 03:23
Ultimately the issue is that the Frigate server is not responding correctly to the client (Home Assistant). Cutting the retention could help as it would reduce the potential response sizes, but I cannot say how much -- and the real fix is in the Frigate server. I'd recommend chiming in on that other bug.

PS: I'm working on changes to how the card gets events from Frigate which may also help with this, but it'll be a while before that's available.

**Comment by HHUBSS** [comment] 2023-01-02 03:30
Thank you. If I choose the camera entity (not the frigate camera entity) it's working fine but I cannot access the clips and snapshots.

![image](https://user-images.githubusercontent.com/89816305/210193237-934300c7-eed4-439b-af07-dd0c9173c650.png)

**Comment by HHUBSS** [comment] 2023-01-02 10:28
UPDATE:

Change retention to 15 days and it's pretty stable now. I think what we need is to show or get only events from the frigate server for xxx days for the frigate card so that we can retain longer records of clips and snapshots on the server.

Thank you so much for your support and I'll wait for the changes your working on. 👍

**Comment by dermotduffy** [comment] 2023-02-27 05:13
I'm going to close this for now -- if after the next build (`v4.1.0`) there are still issues we should re-open. As mentioned, I have considerably re-worked how these fetches are made, and how they are (now) cached, so performance should be better.

**Closed by dermotduffy** 2023-02-27 05:13 UTC
Labels: bug
