### ISSUE TITLE
Improve the JSMPEG live stream loading experience

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#243] opened 2021-12-16 04:06 UTC
**Is your feature request related to a problem? Please describe.**
I'm using JSMPEG live stream, and it always takes some seconds to start displaying:

https://user-images.githubusercontent.com/29582865/146306042-40aaec9e-5896-442a-a7c6-232c858bca35.mp4

If this blank screen is not added by the card itself, I suppose the card could self-detect this state by checking if the screen is white in its majority.

**Describe the solution you'd like**

It would be much more pleasant if this card could display a loading screen before it gets loaded. A simple spinner like WebRTC's one would be already much better, but there is also the option of displaying the latest snapshot, blurred, with a spinner. Or something like that.

**Describe alternatives you've considered**
WebRTC provides a spinner:

https://user-images.githubusercontent.com/29582865/146306350-13695493-d351-44d9-bc06-76be17c88c2f.mp4

Or... at least it tries 😋

**Additional context**

None.

**Comment by dermotduffy** [comment] 2021-12-17 06:04
This is not caused by the card directly, but by the underlying JSMPEG player (e.g. you'll notice the Frigate UI does the same on load). To try to do better on this, I previously had it that a spinner was shown until the JSMPEG player itself reported the video stream was loaded -- but that still resulted in a prolonged 'white' screen, and eventually I concluded it wasn't worth the complexity.

I'll look into it again and see if there's something that can be done, but I'm not super optimistic there is a straightforward fix for this.

**Comment by dermotduffy** [comment] 2021-12-17 21:33
[Having thought a bit more] ...but maybe there's some hack that at least gets rid of the white loading screen (e.g. drawing the Frigate logo onto the canvas before passing it to the player, or using a spinner until a non-blank pixel is found).

**Comment by felipecrs** [comment] 2021-12-18 00:26
That's exactly what I had in mind when I said:

> I suppose the card could self-detect this state by checking if the screen is white in its majority.

By the way, the Frigate logo that is used by your card is pretty amazing.

- Frigate logo
- Spinner
- The latest blurry snapshot for that same camera
- The latest blurry snapshot for that same camera with a spinner on top of it

Either option would be much more stylish than the current white screen, so I think it would be a nice addition.

---

Also, I need to say, your card is amazing. I could not be more pleased to be a user of it, really. It helps the community a lot, so thank you very much!

**Comment by dermotduffy** [comment] 2021-12-18 00:33
> By the way, the Frigate logo that is used by your card is pretty beautiful indeed.

I agree: [Credit to the original photographer](https://github.com/dermotduffy/frigate-hass-card/tree/main/src/images)!

> Frigate logo
> Spinner
> The latest blurry snapshot for that same camera
> The latest blurry snapshot for that same camera with a spinner on top of it

For the record, the issue with the last two are that they both may involve making a network connection -- which _itself_ is an async request that may need a spinner ;-) An advanced version of this could use the latest snapshot if it's available, and otherwise use one of the first two choices, but I think it's simplest just to start with one of the first two for now at least.

> Also, I need to say, your card is amazing. I could not be more pleased to be a user of it, really. It helps the community a lot, so thank you very much!

Thank you very much, really appreciate the kind words and the quality bug reports that help make the card better.

**Comment by felipecrs** [comment] 2021-12-18 00:41
> but I think it's simplest just to start with one of the first two for now at least.

I agree with you!

**Closed** 2022-01-18 04:31 UTC
Labels: enhancement
