### ISSUE TITLE
Video not loading fast enought

### ISSUE THREAD

**Issue by boehser-enkel** [dermotduffy/frigate-hass-card#511] opened 2022-04-14 11:05 UTC
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
3.0.0
**Last working release (if known):**
n/a
**Browser and Operating System:**

Any (Windows 10), Chrome, Firefox

**Description of problem:**

Video feed is not loading fast enought. The view is stuttering and needs to catch up after a few seconds.
When watching the camera.entity within HA it loads fast enough. Also the View in the frigate pane does not have this problem

```

```

**Additional information:**

**Comment by dermotduffy** [comment] 2022-04-15 02:54
Hello,

Thank you for the report. Can you provide your configuration? The camera feed in the card when you're using the `ha` provider, and the camera feed in HA, should perform ~identically (it is using almost exactly the same code). Are you saying this is not the case?

Thanks.

**Comment by boehser-enkel** [comment] 2022-04-16 21:05
> Hello,
> 
> Thank you for the report. Can you provide your configuration? The camera feed in the card when you're using the `ha` provider, and the camera feed in HA, should perform ~identically (it is using almost exactly the same code). Are you saying this is not the case?
> 
> Thanks.

Yes this is what I experience. 

`type: custom:frigate-card
tap_action:
  action: more-info
view:
  default: live
  update_entities:
    - binary_sensor.vorne_person_motion
menu:
  mode: below
  buttons:
    frigate: false
    fullscreen: true
    image: false
event_viewer:
  controls:
    thumbnails:
      mode: none
    next_previous:
      style: thumbnails
  auto_play: false
live:
  preload: true
cameras:
  - camera_entity: camera.vorne
    camera_name: Vorne
    live_provider: ha
    webrtc_card: {}
`

**Comment by dermotduffy** [comment] 2022-04-16 22:00
* If you make a normal picture glance card with `camera.vorne` does it work okay?
* If you remove the `update_entities` section does that make any difference?

**Comment by dermotduffy** [comment] 2022-04-24 05:18
Yes -- if the camera entity has a problem outside of the card, then the issue is not with the card (this repo). It could be either a problem with the [integration](https://github.com/blakeblackshear/frigate-hass-integration) or I think more likely with your Frigate server setup itself.

**Comment by dermotduffy** [comment] 2022-05-01 20:57
Closing for now as I do not believe this issue is related to the card. Please re-open if you conclude it is the card at fault. Thanks.

**Closed by dermotduffy** 2022-05-01 20:57 UTC
Labels: bug
